/**
 * 90个 Hacker News 顶级技术博客 RSS 源
 * 源自 Andrej Karpathy 推荐和 HN 社区精选
 */

export interface RSSSource {
  id: string;
  name: string;
  url: string;
  category: string;
  language: "zh" | "en";
  description?: string;
  isActive: boolean;
}

// Hacker News 顶级技术博客 - 英文源
export const HACKER_NEWS_SOURCES: RSSSource[] = [
  // AI/ML 研究
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    url: "https://openai.com/blog/rss.xml",
    category: "AI/ML",
    language: "en",
    description: "OpenAI 官方博客",
    isActive: true,
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    url: "https://www.anthropic.com/news/rss.xml",
    category: "AI/ML",
    language: "en",
    description: "Anthropic 新闻和研究",
    isActive: true,
  },
  {
    id: "deepmind-blog",
    name: "Google DeepMind Blog",
    url: "https://deepmind.google/blog/rss.xml",
    category: "AI/ML",
    language: "en",
    description: "Google DeepMind 博客",
    isActive: true,
  },
  {
    id: "ai-google",
    name: "Google AI Blog",
    url: "https://ai.googleblog.com/feeds/posts/default",
    category: "AI/ML",
    language: "en",
    description: "Google AI 研究博客",
    isActive: true,
  },
  {
    id: "pytorch-blog",
    name: "PyTorch Blog",
    url: "https://pytorch.org/blog/rss.xml",
    category: "AI/ML",
    language: "en",
    description: "PyTorch 官方博客",
    isActive: true,
  },
  {
    id: "tensorflow-blog",
    name: "TensorFlow Blog",
    url: "https://blog.tensorflow.org/feeds/posts/default",
    category: "AI/ML",
    language: "en",
    description: "TensorFlow 官方博客",
    isActive: true,
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    url: "https://huggingface.co/blog/feed.xml",
    category: "AI/ML",
    language: "en",
    description: "Hugging Face 博客",
    isActive: true,
  },
  {
    id: "arxiv-csai",
    name: "arXiv AI",
    url: "http://export.arxiv.org/rss/cs.AI",
    category: "AI/ML",
    language: "en",
    description: "arXiv 人工智能论文",
    isActive: true,
  },
  {
    id: "arxiv-cv",
    name: "arXiv Computer Vision",
    url: "http://export.arxiv.org/rss/cs.CV",
    category: "AI/ML",
    language: "en",
    description: "arXiv 计算机视觉论文",
    isActive: true,
  },
  {
    id: "arxiv-lg",
    name: "arXiv Machine Learning",
    url: "http://export.arxiv.org/rss/cs.LG",
    category: "AI/ML",
    language: "en",
    description: "arXiv 机器学习论文",
    isActive: true,
  },
  {
    id: "baai",
    name: "BAAI",
    url: "https://www.baai.ac.cn/news.xml",
    category: "AI/ML",
    language: "en",
    description: "北京智源人工智能研究院",
    isActive: true,
  },
  {
    id: "ai-jenning",
    name: "AI Explained",
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCNJ1Ymd5yFuUPtn21xtRbbw",
    category: "AI/ML",
    language: "en",
    description: "AI Explained",
    isActive: true,
  },
  
  // 工程/系统
  {
    id: "netflix-tech",
    name: "Netflix Tech Blog",
    url: "https://netflixtechblog.com/feed",
    category: "工程",
    language: "en",
    description: "Netflix 技术博客",
    isActive: true,
  },
  {
    id: "uber-engineering",
    name: "Uber Engineering",
    url: "https://www.uber.com/en-US/blog/engineering/rss/",
    category: "工程",
    language: "en",
    description: "Uber 工程博客",
    isActive: true,
  },
  {
    id: "meta-engineering",
    name: "Meta Engineering",
    url: "https://engineering.fb.com/feed/",
    category: "工程",
    language: "en",
    description: "Meta 工程博客",
    isActive: true,
  },
  {
    id: "stripe-blog",
    name: "Stripe Blog",
    url: "https://stripe.com/blog/rss.xml",
    category: "工程",
    language: "en",
    description: "Stripe 博客",
    isActive: true,
  },
  {
    id: "airbnb-engineering",
    name: "Airbnb Engineering",
    url: "https://medium.com/feed/airbnb-engineering",
    category: "工程",
    language: "en",
    description: "Airbnb 工程博客",
    isActive: true,
  },
  {
    id: "spotify-engineering",
    name: "Spotify Engineering",
    url: "https://engineering.atspotify.com/feed/",
    category: "工程",
    language: "en",
    description: "Spotify 工程博客",
    isActive: true,
  },
  {
    id: "linkedin-engineering",
    name: "LinkedIn Engineering",
    url: "https://engineering.linkedin.com/blog.rss",
    category: "工程",
    language: "en",
    description: "LinkedIn 工程博客",
    isActive: true,
  },
  {
    id: "dropbox-tech",
    name: "Dropbox Tech Blog",
    url: "https://dropbox.tech/feed",
    category: "工程",
    language: "en",
    description: "Dropbox 技术博客",
    isActive: true,
  },
  {
    id: "cloudflare-blog",
    name: "Cloudflare Blog",
    url: "https://blog.cloudflare.com/rss/",
    category: "工程",
    language: "en",
    description: "Cloudflare 博客",
    isActive: true,
  },
  {
    id: "aws-blog",
    name: "AWS News Blog",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    category: "工程",
    language: "en",
    description: "AWS 新闻博客",
    isActive: true,
  },
  {
    id: "google-cloud-blog",
    name: "Google Cloud Blog",
    url: "https://cloud.google.com/blog/rss",
    category: "工程",
    language: "en",
    description: "Google Cloud 博客",
    isActive: true,
  },
  {
    id: "azure-blog",
    name: "Azure Blog",
    url: "https://azure.microsoft.com/en-us/blog/feed/",
    category: "工程",
    language: "en",
    description: "Microsoft Azure 博客",
    isActive: true,
  },
  
  // 开发工具/开源
  {
    id: "github-blog",
    name: "GitHub Blog",
    url: "https://github.blog/feed/",
    category: "开源",
    language: "en",
    description: "GitHub 官方博客",
    isActive: true,
  },
  {
    id: "gitlab-blog",
    name: "GitLab Blog",
    url: "https://about.gitlab.com/blog/index.xml",
    category: "开源",
    language: "en",
    description: "GitLab 博客",
    isActive: true,
  },
  {
    id: "rust-blog",
    name: "Rust Blog",
    url: "https://blog.rust-lang.org/feed.xml",
    category: "开源",
    language: "en",
    description: "Rust 语言博客",
    isActive: true,
  },
  {
    id: "golang-blog",
    name: "Go Blog",
    url: "https://go.dev/blog/feed.atom",
    category: "开源",
    language: "en",
    description: "Go 语言博客",
    isActive: true,
  },
  {
    id: "react-blog",
    name: "React Blog",
    url: "https://react.dev/rss.xml",
    category: "开源",
    language: "en",
    description: "React 官方博客",
    isActive: true,
  },
  {
    id: "vercel-blog",
    name: "Vercel Blog",
    url: "https://vercel.com/blog/rss.xml",
    category: "开源",
    language: "en",
    description: "Vercel 博客",
    isActive: true,
  },
  {
    id: "deno-blog",
    name: "Deno Blog",
    url: "https://deno.com/feed",
    category: "开源",
    language: "en",
    description: "Deno 博客",
    isActive: true,
  },
  {
    id: "nodejs-blog",
    name: "Node.js Blog",
    url: "https://nodejs.org/en/feed/blog.xml",
    category: "开源",
    language: "en",
    description: "Node.js 博客",
    isActive: true,
  },
  {
    id: "npm-blog",
    name: "npm Blog",
    url: "https://blog.npmjs.org/rss",
    category: "开源",
    language: "en",
    description: "npm 博客",
    isActive: true,
  },
  {
    id: "docker-blog",
    name: "Docker Blog",
    url: "https://www.docker.com/blog/feed/",
    category: "开源",
    language: "en",
    description: "Docker 博客",
    isActive: true,
  },
  {
    id: "kubernetes-blog",
    name: "Kubernetes Blog",
    url: "https://kubernetes.io/feed.xml",
    category: "开源",
    language: "en",
    description: "Kubernetes 博客",
    isActive: true,
  },
  {
    id: "prometheus-blog",
    name: "Prometheus Blog",
    url: "https://prometheus.io/blog/feed.xml",
    category: "开源",
    language: "en",
    description: "Prometheus 博客",
    isActive: true,
  },
  
  // 安全
  {
    id: "google-security",
    name: "Google Security Blog",
    url: "https://security.googleblog.com/feeds/posts/default",
    category: "安全",
    language: "en",
    description: "Google 安全博客",
    isActive: true,
  },
  {
    id: "cloudflare-security",
    name: "Cloudflare Security",
    url: "https://blog.cloudflare.com/tag/security/rss/",
    category: "安全",
    language: "en",
    description: "Cloudflare 安全博客",
    isActive: true,
  },
  {
    id: "microsoft-security",
    name: "Microsoft Security",
    url: "https://www.microsoft.com/security/blog/feed/",
    category: "安全",
    language: "en",
    description: "Microsoft 安全博客",
    isActive: true,
  },
  {
    id: "aws-security",
    name: "AWS Security Blog",
    url: "https://aws.amazon.com/blogs/security/feed/",
    category: "安全",
    language: "en",
    description: "AWS 安全博客",
    isActive: true,
  },
  
  // 数据库/基础设施
  {
    id: "postgres-blog",
    name: "PostgreSQL News",
    url: "https://www.postgresql.org/news.rss",
    category: "工具",
    language: "en",
    description: "PostgreSQL 新闻",
    isActive: true,
  },
  {
    id: "mysql-blog",
    name: "MySQL Blog",
    url: "https://blogs.oracle.com/mysql/rss",
    category: "工具",
    language: "en",
    description: "MySQL 博客",
    isActive: true,
  },
  {
    id: "mongodb-blog",
    name: "MongoDB Blog",
    url: "https://www.mongodb.com/blog/rss",
    category: "工具",
    language: "en",
    description: "MongoDB 博客",
    isActive: true,
  },
  {
    id: "redis-blog",
    name: "Redis Blog",
    url: "https://redis.io/blog/feed.xml",
    category: "工具",
    language: "en",
    description: "Redis 博客",
    isActive: true,
  },
  {
    id: "elastic-blog",
    name: "Elastic Blog",
    url: "https://www.elastic.co/blog/feed",
    category: "工具",
    language: "en",
    description: "Elastic 博客",
    isActive: true,
  },
  {
    id: "kafka-blog",
    name: "Confluent Blog",
    url: "https://www.confluent.io/blog/feed/",
    category: "工具",
    language: "en",
    description: "Confluent/Kafka 博客",
    isActive: true,
  },
  
  // 技术媒体
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    category: "观点",
    language: "en",
    description: "TechCrunch 科技新闻",
    isActive: true,
  },
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    category: "AI/ML",
    language: "en",
    description: "TechCrunch AI 专栏",
    isActive: true,
  },
  {
    id: "the-verge",
    name: "The Verge",
    url: "https://www.theverge.com/rss/index.xml",
    category: "观点",
    language: "en",
    description: "The Verge 科技新闻",
    isActive: true,
  },
  {
    id: "wired",
    name: "Wired",
    url: "https://www.wired.com/feed/rss",
    category: "观点",
    language: "en",
    description: "Wired 科技杂志",
    isActive: true,
  },
  {
    id: "ars-technica",
    name: "Ars Technica",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    category: "观点",
    language: "en",
    description: "Ars Technica 科技新闻",
    isActive: true,
  },
  {
    id: "hacker-news",
    name: "Hacker News",
    url: "https://hnrss.org/frontpage",
    category: "观点",
    language: "en",
    description: "Hacker News 热门",
    isActive: true,
  },
  {
    id: "slashdot",
    name: "Slashdot",
    url: "http://rss.slashdot.org/Slashdot/slashdot",
    category: "观点",
    language: "en",
    description: "Slashdot 科技新闻",
    isActive: true,
  },
  {
    id: "lobsters",
    name: "Lobsters",
    url: "https://lobste.rs/rss",
    category: "观点",
    language: "en",
    description: "Lobsters 技术社区",
    isActive: true,
  },
  
  // 开发者博客
  {
    id: "martin-fowler",
    name: "Martin Fowler",
    url: "https://martinfowler.com/feed.atom",
    category: "观点",
    language: "en",
    description: "Martin Fowler 博客",
    isActive: true,
  },
  {
    id: "joel-spolsky",
    name: "Joel on Software",
    url: "https://www.joelonsoftware.com/feed/",
    category: "观点",
    language: "en",
    description: "Joel Spolsky 博客",
    isActive: true,
  },
  {
    id: "paul-graham",
    name: "Paul Graham",
    url: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
    category: "观点",
    language: "en",
    description: "Paul Graham  essays",
    isActive: true,
  },
  {
    id: "dan-luu",
    name: "Dan Luu",
    url: "https://danluu.com/atom.xml",
    category: "观点",
    language: "en",
    description: "Dan Luu 博客",
    isActive: true,
  },
  {
    id: "julia-evans",
    name: "Julia Evans",
    url: "https://jvns.ca/atom.xml",
    category: "观点",
    language: "en",
    description: "Julia Evans 博客",
    isActive: true,
  },
  {
    id: "rachel-by-the-bay",
    name: "rachel by the bay",
    url: "https://rachelbythebay.com/w/atom.xml",
    category: "观点",
    language: "en",
    description: "rachel by the bay",
    isActive: true,
  },
  {
    id: "high-scalability",
    name: "High Scalability",
    url: "http://feeds.feedburner.com/HighScalability",
    category: "工程",
    language: "en",
    description: "High Scalability",
    isActive: true,
  },
  
  // 编程语言/框架
  {
    id: "llvm-blog",
    name: "LLVM Blog",
    url: "https://blog.llvm.org/rss.xml",
    category: "工具",
    language: "en",
    description: "LLVM 博客",
    isActive: true,
  },
  {
    id: "webkit-blog",
    name: "WebKit Blog",
    url: "https://webkit.org/rss.xml",
    category: "工具",
    language: "en",
    description: "WebKit 博客",
    isActive: true,
  },
  {
    id: "v8-blog",
    name: "V8 Blog",
    url: "https://v8.dev/blog.atom",
    category: "工具",
    language: "en",
    description: "V8 JavaScript 引擎博客",
    isActive: true,
  },
  {
    id: "mozilla-hacks",
    name: "Mozilla Hacks",
    url: "https://hacks.mozilla.org/feed/",
    category: "开源",
    language: "en",
    description: "Mozilla Hacks",
    isActive: true,
  },
  {
    id: "webkit-status",
    name: "WebKit Status",
    url: "https://webkit.org/status/rss.xml",
    category: "工具",
    language: "en",
    description: "WebKit 状态更新",
    isActive: true,
  },
  
  // 其他重要技术博客
  {
    id: "acm-queue",
    name: "ACM Queue",
    url: "https://queue.acm.org/rss/feeds/queuecontent.xml",
    category: "观点",
    language: "en",
    description: "ACM Queue",
    isActive: true,
  },
  {
    id: "infoq",
    name: "InfoQ",
    url: "https://www.infoq.com/feed/",
    category: "观点",
    language: "en",
    description: "InfoQ 技术新闻",
    isActive: true,
  },
  {
    id: "dzone",
    name: "DZone",
    url: "https://feeds.dzone.com/home",
    category: "观点",
    language: "en",
    description: "DZone 开发者社区",
    isActive: true,
  },
  {
    id: "smashing-magazine",
    name: "Smashing Magazine",
    url: "https://www.smashingmagazine.com/feed/",
    category: "工具",
    language: "en",
    description: "Smashing Magazine",
    isActive: true,
  },
  {
    id: "css-tricks",
    name: "CSS-Tricks",
    url: "https://css-tricks.com/feed/",
    category: "工具",
    language: "en",
    description: "CSS-Tricks",
    isActive: true,
  },
  {
    id: "web-dev",
    name: "web.dev",
    url: "https://web.dev/feed.xml",
    category: "工具",
    language: "en",
    description: "Google web.dev",
    isActive: true,
  },
  {
    id: "devtools-blog",
    name: "Chrome DevTools",
    url: "https://developer.chrome.com/tags/devtools/feed.xml",
    category: "工具",
    language: "en",
    description: "Chrome DevTools",
    isActive: true,
  },
  {
    id: "stack-overflow",
    name: "Stack Overflow Blog",
    url: "https://stackoverflow.blog/feed/",
    category: "观点",
    language: "en",
    description: "Stack Overflow 博客",
    isActive: true,
  },
  {
    id: "github-security",
    name: "GitHub Security",
    url: "https://github.blog/tag/security/feed/",
    category: "安全",
    language: "en",
    description: "GitHub 安全博客",
    isActive: true,
  },
];

// 中文科技媒体源
export const CHINESE_SOURCES: RSSSource[] = [
  {
    id: "36kr-ai",
    name: "36氪 AI",
    url: "https://36kr.com/feed-news.xml",
    category: "观点",
    language: "zh",
    description: "36氪科技新闻",
    isActive: true,
  },
  {
    id: "pingwest",
    name: "品玩",
    url: "https://www.pingwest.com/feed",
    category: "观点",
    language: "zh",
    description: "品玩科技媒体",
    isActive: true,
  },
  {
    id: "solidot",
    name: "Solidot",
    url: "https://www.solidot.org/index.rss",
    category: "观点",
    language: "zh",
    description: "Solidot 科技新闻",
    isActive: true,
  },
  {
    id: "ifanr",
    name: "爱范儿",
    url: "https://www.ifanr.com/feed",
    category: "观点",
    language: "zh",
    description: "爱范儿科技媒体",
    isActive: true,
  },
  {
    id: "geekpark",
    name: "极客公园",
    url: "https://www.geekpark.net/rss",
    category: "观点",
    language: "zh",
    description: "极客公园",
    isActive: true,
  },
  {
    id: "机器之心",
    name: "机器之心",
    url: "https://www.jiqizhixin.com/rss",
    category: "AI/ML",
    language: "zh",
    description: "机器之心 AI 媒体",
    isActive: true,
  },
  {
    id: "量子位",
    name: "量子位",
    url: "https://www.qbitai.com/feed",
    category: "AI/ML",
    language: "zh",
    description: "量子位 AI 媒体",
    isActive: true,
  },
  {
    id: "infoq-cn",
    name: "InfoQ 中文",
    url: "https://www.infoq.cn/feed/",
    category: "工程",
    language: "zh",
    description: "InfoQ 中文站",
    isActive: true,
  },
  {
    id: "oschina",
    name: "开源中国",
    url: "https://www.oschina.net/news/rss",
    category: "开源",
    language: "zh",
    description: "开源中国社区",
    isActive: true,
  },
  {
    id: "segmentfault",
    name: "SegmentFault",
    url: "https://segmentfault.com/feeds/blogs",
    category: "工程",
    language: "zh",
    description: "SegmentFault 社区",
    isActive: true,
  },
  {
    id: "csdn",
    name: "CSDN 资讯",
    url: "https://blog.csdn.net/rss.html",
    category: "工程",
    language: "zh",
    description: "CSDN 资讯",
    isActive: true,
  },
  {
    id: "zhihu-daily",
    name: "知乎日报",
    url: "https://daily.zhihu.com/rss",
    category: "观点",
    language: "zh",
    description: "知乎日报",
    isActive: true,
  },
  {
    id: "sspai",
    name: "少数派",
    url: "https://sspai.com/feed",
    category: "工具",
    language: "zh",
    description: "少数派科技媒体",
    isActive: true,
  },
  {
    id: "uisdc",
    name: "优设",
    url: "https://www.uisdc.com/feed",
    category: "工具",
    language: "zh",
    description: "优设设计社区",
    isActive: true,
  },
  {
    id: "techweb",
    name: "TechWeb",
    url: "http://www.techweb.com.cn/rss/hot.xml",
    category: "观点",
    language: "zh",
    description: "TechWeb 科技新闻",
    isActive: true,
  },
  {
    id: "cnbeta",
    name: "cnBeta",
    url: "https://www.cnbeta.com/backend.php",
    category: "观点",
    language: "zh",
    description: "cnBeta 科技新闻",
    isActive: true,
  },
  {
    id: "ithome",
    name: "IT之家",
    url: "https://www.ithome.com/rss/",
    category: "观点",
    language: "zh",
    description: "IT之家科技新闻",
    isActive: true,
  },
  {
    id: "leiphone",
    name: "雷锋网",
    url: "https://www.leiphone.com/feed",
    category: "AI/ML",
    language: "zh",
    description: "雷锋网 AI 媒体",
    isActive: true,
  },
  {
    id: "synced",
    name: "Synced",
    url: "https://syncedreview.com/feed/",
    category: "AI/ML",
    language: "zh",
    description: "Synced AI 评论",
    isActive: true,
  },
  {
    id: "ai-frontier",
    name: "AI 前线",
    url: "https://www.infoq.cn/topic/AI/feed",
    category: "AI/ML",
    language: "zh",
    description: "AI 前线",
    isActive: true,
  },
];

// 合并所有数据源
export const ALL_RSS_SOURCES: RSSSource[] = [
  ...HACKER_NEWS_SOURCES,
  ...CHINESE_SOURCES,
];

// 按分类获取数据源
export function getSourcesByCategory(category: string): RSSSource[] {
  return ALL_RSS_SOURCES.filter(s => s.category === category && s.isActive);
}

// 按语言获取数据源
export function getSourcesByLanguage(language: "zh" | "en"): RSSSource[] {
  return ALL_RSS_SOURCES.filter(s => s.language === language && s.isActive);
}

// 获取活跃数据源
export function getActiveSources(): RSSSource[] {
  return ALL_RSS_SOURCES.filter(s => s.isActive);
}
