/**
 * RSS 数据源配置
 * 包含 100+ AI 相关数据源：英文权威源、中文权威源、社交媒体/社区
 */

export type SourcePriority = "high" | "medium" | "low";
export type SourceType = "official" | "media" | "community" | "academic" | "social";

export interface RSSSource {
  id: string;
  name: string;
  xmlUrl: string;
  htmlUrl: string;
  language: "zh" | "en";
  category: string;
  priority: SourcePriority;
  type: SourceType;
  isActive: boolean;
  lastCrawled?: string;
}

// ============ 英文权威源 - AI 公司官方博客 (50+) ============

// RSSHub 实例列表
const RSSHUB_INSTANCES = [
  "https://rsshub.rssforever.com",
  "https://rsshub.freedit.eu",
  "https://rsshub.pseudoyu.com",
];

// 获取 RSSHub URL
function getRsshubUrl(path: string): string {
  const instance = RSSHUB_INSTANCES[Math.floor(Math.random() * RSSHUB_INSTANCES.length)];
  return `${instance}${path}`;
}

// 大模型公司官方博客 - 高频更新
export const AI_COMPANY_BLOGS: RSSSource[] = [
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    xmlUrl: "https://openai.com/blog/rss.xml",
    htmlUrl: "https://openai.com/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "openai-research",
    name: "OpenAI Research",
    xmlUrl: "https://openai.com/research/rss.xml",
    htmlUrl: "https://openai.com/research",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: false, // 404 - RSS discontinued
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    xmlUrl: getRsshubUrl("/anthropic/news"),
    htmlUrl: "https://www.anthropic.com/news",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    xmlUrl: getRsshubUrl("/anthropic/research"),
    htmlUrl: "https://www.anthropic.com/research",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    xmlUrl: getRsshubUrl("/google/research"),
    htmlUrl: "https://ai.googleblog.com",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "deepmind-blog",
    name: "DeepMind Blog",
    xmlUrl: "https://deepmind.google/blog/rss.xml",
    htmlUrl: "https://deepmind.google/blog",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Blog",
    xmlUrl: getRsshubUrl("/meta/ai"),
    htmlUrl: "https://ai.meta.com/blog",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "xai-blog",
    name: "xAI Blog",
    xmlUrl: "https://x.ai/blog/rss.xml",
    htmlUrl: "https://x.ai/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: false, // 403 Forbidden - blocked
  },
  {
    id: "mistral-blog",
    name: "Mistral AI Blog",
    xmlUrl: getRsshubUrl("/mistral/blog"),
    htmlUrl: "https://mistral.ai/news",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "cohere-blog",
    name: "Cohere Blog",
    xmlUrl: getRsshubUrl("/cohere/blog"),
    htmlUrl: "https://cohere.com/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    xmlUrl: "https://huggingface.co/blog/feed.xml",
    htmlUrl: "https://huggingface.co/blog",
    language: "en",
    category: "开源社区",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "stability-blog",
    name: "Stability AI Blog",
    xmlUrl: getRsshubUrl("/stability/blog"),
    htmlUrl: "https://stability.ai/blog",
    language: "en",
    category: "多模态",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA AI Blog",
    xmlUrl: getRsshubUrl("/nvidia/blog"),
    htmlUrl: "https://blogs.nvidia.com/blog/ai",
    language: "en",
    category: "AI芯片",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "microsoft-ai-blog",
    name: "Microsoft AI Blog",
    xmlUrl: getRsshubUrl("/microsoft/ai"),
    htmlUrl: "https://blogs.microsoft.com/ai",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: false, // RSSHub unstable
  },
  // 高质量科技媒体 - 英文
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    xmlUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    htmlUrl: "https://techcrunch.com/category/artificial-intelligence/",
    language: "en",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "the-verge",
    name: "The Verge",
    xmlUrl: "https://www.theverge.com/rss/index.xml",
    htmlUrl: "https://www.theverge.com",
    language: "en",
    category: "科技媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "ars-technica-ai",
    name: "Ars Technica AI",
    xmlUrl: "https://arstechnica.com/tag/ai/feed/",
    htmlUrl: "https://arstechnica.com/tag/ai/",
    language: "en",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "wired-ai",
    name: "Wired AI",
    xmlUrl: "https://www.wired.com/feed/tag/ai/latest/rss",
    htmlUrl: "https://www.wired.com/tag/ai/",
    language: "en",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
    type: "official",
    isActive: false, // RSSHub unstable
  },
  {
    id: "amazon-ai-blog",
    name: "AWS AI Blog",
    xmlUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    htmlUrl: "https://aws.amazon.com/blogs/machine-learning",
    language: "en",
    category: "云服务",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "ai2-blog",
    name: "AI2 Blog",
    xmlUrl: "https://blog.allenai.org/feed",
    htmlUrl: "https://blog.allenai.org",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "baidu-research",
    name: "Baidu Research",
    xmlUrl: "http://research.baidu.com/feed",
    htmlUrl: "http://research.baidu.com",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "alibaba-damo",
    name: "Alibaba DAMO Academy",
    xmlUrl: "https://damo.alibaba.com/rss",
    htmlUrl: "https://damo.alibaba.com",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "perplexity-blog",
    name: "Perplexity Blog",
    xmlUrl: "https://www.perplexity.ai/hub/blog/rss.xml",
    htmlUrl: "https://www.perplexity.ai/hub/blog",
    language: "en",
    category: "AI搜索",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "cursor-blog",
    name: "Cursor Blog",
    xmlUrl: "https://cursor.com/blog/rss.xml",
    htmlUrl: "https://cursor.com/blog",
    language: "en",
    category: "AI编程",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "replicate-blog",
    name: "Replicate Blog",
    xmlUrl: "https://replicate.com/blog/rss.xml",
    htmlUrl: "https://replicate.com/blog",
    language: "en",
    category: "AI模型托管",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "groq-blog",
    name: "Groq Blog",
    xmlUrl: "https://groq.com/blog/rss/",
    htmlUrl: "https://groq.com/blog",
    language: "en",
    category: "AI芯片",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "fireworks-ai-blog",
    name: "Fireworks AI Blog",
    xmlUrl: "https://fireworks.ai/blog/rss.xml",
    htmlUrl: "https://fireworks.ai/blog",
    language: "en",
    category: "AI推理",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "together-ai-blog",
    name: "Together AI Blog",
    xmlUrl: "https://www.together.ai/blog/rss.xml",
    htmlUrl: "https://www.together.ai/blog",
    language: "en",
    category: "AI推理",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "anyscale-blog",
    name: "Anyscale Blog",
    xmlUrl: "https://www.anyscale.com/blog/rss.xml",
    htmlUrl: "https://www.anyscale.com/blog",
    language: "en",
    category: "AI基础设施",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "baseten-blog",
    name: "Baseten Blog",
    xmlUrl: "https://www.baseten.co/blog/rss.xml",
    htmlUrl: "https://www.baseten.co/blog",
    language: "en",
    category: "MLOps",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "modal-blog",
    name: "Modal Blog",
    xmlUrl: "https://modal.com/blog/rss.xml",
    htmlUrl: "https://modal.com/blog",
    language: "en",
    category: "AI基础设施",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "runpod-blog",
    name: "RunPod Blog",
    xmlUrl: "https://blog.runpod.io/rss/",
    htmlUrl: "https://blog.runpod.io",
    language: "en",
    category: "AI基础设施",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "deepinfra-blog",
    name: "DeepInfra Blog",
    xmlUrl: "https://deepinfra.com/blog/rss.xml",
    htmlUrl: "https://deepinfra.com/blog",
    language: "en",
    category: "AI推理",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "octoai-blog",
    name: "OctoAI Blog",
    xmlUrl: "https://octo.ai/blog/rss.xml",
    htmlUrl: "https://octo.ai/blog",
    language: "en",
    category: "AI推理",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "predibase-blog",
    name: "Predibase Blog",
    xmlUrl: "https://predibase.com/blog/rss.xml",
    htmlUrl: "https://predibase.com/blog",
    language: "en",
    category: "LLM微调",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "arize-blog",
    name: "Arize AI Blog",
    xmlUrl: "https://arize.com/blog/feed/",
    htmlUrl: "https://arize.com/blog",
    language: "en",
    category: "AI可观测性",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "langfuse-blog",
    name: "Langfuse Blog",
    xmlUrl: "https://langfuse.com/blog/rss.xml",
    htmlUrl: "https://langfuse.com/blog",
    language: "en",
    category: "LLM可观测性",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "braintrust-blog",
    name: "Braintrust Blog",
    xmlUrl: "https://www.braintrust.dev/blog/rss.xml",
    htmlUrl: "https://www.braintrust.dev/blog",
    language: "en",
    category: "AI评估",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "humanloop-blog",
    name: "Humanloop Blog",
    xmlUrl: "https://humanloop.com/blog/rss.xml",
    htmlUrl: "https://humanloop.com/blog",
    language: "en",
    category: "LLM开发平台",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "openpipe-blog",
    name: "OpenPipe Blog",
    xmlUrl: "https://openpipe.ai/blog/rss.xml",
    htmlUrl: "https://openpipe.ai/blog",
    language: "en",
    category: "LLM微调",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "lastmile-ai-blog",
    name: "LastMile AI Blog",
    xmlUrl: "https://lastmileai.dev/blog/rss.xml",
    htmlUrl: "https://lastmileai.dev/blog",
    language: "en",
    category: "AI工程",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "promptlayer-blog",
    name: "PromptLayer Blog",
    xmlUrl: "https://promptlayer.com/blog/rss.xml",
    htmlUrl: "https://promptlayer.com/blog",
    language: "en",
    category: "Prompt工程",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "traceloop-blog",
    name: "Traceloop Blog",
    xmlUrl: "https://www.traceloop.com/blog/rss.xml",
    htmlUrl: "https://www.traceloop.com/blog",
    language: "en",
    category: "LLM可观测性",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "helicone-blog",
    name: "Helicone Blog",
    xmlUrl: "https://www.helicone.ai/blog/rss.xml",
    htmlUrl: "https://www.helicone.ai/blog",
    language: "en",
    category: "LLM可观测性",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "portkey-blog",
    name: "Portkey Blog",
    xmlUrl: "https://portkey.ai/blog/rss.xml",
    htmlUrl: "https://portkey.ai/blog",
    language: "en",
    category: "AI网关",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "lunary-blog",
    name: "Lunary Blog",
    xmlUrl: "https://lunary.ai/blog/rss.xml",
    htmlUrl: "https://lunary.ai/blog",
    language: "en",
    category: "LLM可观测性",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "context-ai-blog",
    name: "Context AI Blog",
    xmlUrl: "https://context.ai/blog/rss.xml",
    htmlUrl: "https://context.ai/blog",
    language: "en",
    category: "AI分析",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "parea-blog",
    name: "Parea Blog",
    xmlUrl: "https://www.parea.ai/blog/rss.xml",
    htmlUrl: "https://www.parea.ai/blog",
    language: "en",
    category: "AI评估",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "weaviate-blog",
    name: "Weaviate Blog",
    xmlUrl: "https://weaviate.io/blog/rss.xml",
    htmlUrl: "https://weaviate.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "pinecone-blog",
    name: "Pinecone Blog",
    xmlUrl: "https://www.pinecone.io/blog/feed/",
    htmlUrl: "https://www.pinecone.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "chroma-blog",
    name: "Chroma Blog",
    xmlUrl: "https://www.trychroma.com/blog/rss.xml",
    htmlUrl: "https://www.trychroma.com/blog",
    language: "en",
    category: "向量数据库",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "qdrant-blog",
    name: "Qdrant Blog",
    xmlUrl: "https://qdrant.tech/blog/rss.xml",
    htmlUrl: "https://qdrant.tech/blog",
    language: "en",
    category: "向量数据库",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "milvus-blog",
    name: "Milvus Blog",
    xmlUrl: "https://milvus.io/blog/rss.xml",
    htmlUrl: "https://milvus.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "pgvector-blog",
    name: "pgvector Blog",
    xmlUrl: "https://jkatz05.com/blog/rss.xml",
    htmlUrl: "https://jkatz05.com/blog",
    language: "en",
    category: "向量数据库",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "autogen-blog",
    name: "AutoGen Blog",
    xmlUrl: "https://microsoft.github.io/autogen/blog/rss.xml",
    htmlUrl: "https://microsoft.github.io/autogen/blog",
    language: "en",
    category: "AI Agent",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "crewai-blog",
    name: "CrewAI Blog",
    xmlUrl: "https://www.crewai.com/blog/rss.xml",
    htmlUrl: "https://www.crewai.com/blog",
    language: "en",
    category: "AI Agent",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "dify-blog",
    name: "Dify Blog",
    xmlUrl: "https://dify.ai/blog/rss.xml",
    htmlUrl: "https://dify.ai/blog",
    language: "en",
    category: "LLM应用开发",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "langflow-blog",
    name: "Langflow Blog",
    xmlUrl: "https://docs.langflow.org/blog/rss.xml",
    htmlUrl: "https://docs.langflow.org/blog",
    language: "en",
    category: "AI工作流",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "flowise-blog",
    name: "Flowise Blog",
    xmlUrl: "https://blog.flowiseai.com/rss",
    htmlUrl: "https://blog.flowiseai.com",
    language: "en",
    category: "AI工作流",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "n8n-blog",
    name: "n8n Blog",
    xmlUrl: "https://blog.n8n.io/rss/",
    htmlUrl: "https://blog.n8n.io",
    language: "en",
    category: "自动化",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "make-blog",
    name: "Make Blog",
    xmlUrl: "https://www.make.com/en/blog/rss.xml",
    htmlUrl: "https://www.make.com/en/blog",
    language: "en",
    category: "自动化",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "zapier-blog",
    name: "Zapier Blog",
    xmlUrl: "https://zapier.com/blog/rss.xml",
    htmlUrl: "https://zapier.com/blog",
    language: "en",
    category: "自动化",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "vapi-blog",
    name: "Vapi Blog",
    xmlUrl: "https://vapi.ai/blog/rss.xml",
    htmlUrl: "https://vapi.ai/blog",
    language: "en",
    category: "Voice AI",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "retell-blog",
    name: "Retell AI Blog",
    xmlUrl: "https://www.retellai.com/blog/rss.xml",
    htmlUrl: "https://www.retellai.com/blog",
    language: "en",
    category: "Voice AI",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "bland-blog",
    name: "Bland AI Blog",
    xmlUrl: "https://www.bland.ai/blog/rss.xml",
    htmlUrl: "https://www.bland.ai/blog",
    language: "en",
    category: "Voice AI",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "elevenlabs-blog",
    name: "ElevenLabs Blog",
    xmlUrl: "https://elevenlabs.io/blog/rss.xml",
    htmlUrl: "https://elevenlabs.io/blog",
    language: "en",
    category: "Voice AI",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "deepgram-blog",
    name: "Deepgram Blog",
    xmlUrl: "https://blog.deepgram.com/rss/",
    htmlUrl: "https://blog.deepgram.com",
    language: "en",
    category: "Voice AI",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "assemblyai-blog",
    name: "AssemblyAI Blog",
    xmlUrl: "https://www.assemblyai.com/blog/rss/",
    htmlUrl: "https://www.assemblyai.com/blog",
    language: "en",
    category: "Voice AI",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "playht-blog",
    name: "PlayHT Blog",
    xmlUrl: "https://play.ht/blog/rss/",
    htmlUrl: "https://play.ht/blog",
    language: "en",
    category: "Voice AI",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "cartesia-blog",
    name: "Cartesia Blog",
    xmlUrl: "https://cartesia.ai/blog/rss.xml",
    htmlUrl: "https://cartesia.ai/blog",
    language: "en",
    category: "Voice AI",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "hume-ai-blog",
    name: "Hume AI Blog",
    xmlUrl: "https://hume.ai/blog/rss.xml",
    htmlUrl: "https://hume.ai/blog",
    language: "en",
    category: "情感AI",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "synthesia-blog",
    name: "Synthesia Blog",
    xmlUrl: "https://www.synthesia.io/blog/rss.xml",
    htmlUrl: "https://www.synthesia.io/blog",
    language: "en",
    category: "AI视频",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "heygen-blog",
    name: "HeyGen Blog",
    xmlUrl: "https://heygen.com/blog/rss.xml",
    htmlUrl: "https://heygen.com/blog",
    language: "en",
    category: "AI视频",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "runway-blog",
    name: "Runway Blog",
    xmlUrl: "https://runwayml.com/blog/rss.xml",
    htmlUrl: "https://runwayml.com/blog",
    language: "en",
    category: "AI视频",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "pika-blog",
    name: "Pika Labs Blog",
    xmlUrl: "https://pika.art/blog/rss.xml",
    htmlUrl: "https://pika.art/blog",
    language: "en",
    category: "AI视频",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "luma-ai-blog",
    name: "Luma AI Blog",
    xmlUrl: "https://lumalabs.ai/blog/rss.xml",
    htmlUrl: "https://lumalabs.ai/blog",
    language: "en",
    category: "3D AI",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "leonardo-ai-blog",
    name: "Leonardo AI Blog",
    xmlUrl: "https://leonardo.ai/blog/rss.xml",
    htmlUrl: "https://leonardo.ai/blog",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "ideogram-blog",
    name: "Ideogram Blog",
    xmlUrl: "https://ideogram.ai/blog/rss.xml",
    htmlUrl: "https://ideogram.ai/blog",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "krea-blog",
    name: "Krea Blog",
    xmlUrl: "https://www.krea.ai/blog/rss.xml",
    htmlUrl: "https://www.krea.ai/blog",
    language: "en",
    category: "AI绘画",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "freepik-blog",
    name: "Freepik Blog",
    xmlUrl: "https://www.freepik.com/blog/rss",
    htmlUrl: "https://www.freepik.com/blog",
    language: "en",
    category: "AI绘画",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "clipdrop-blog",
    name: "Clipdrop Blog",
    xmlUrl: "https://clipdrop.co/blog/rss.xml",
    htmlUrl: "https://clipdrop.co/blog",
    language: "en",
    category: "AI绘画",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "photoroom-blog",
    name: "PhotoRoom Blog",
    xmlUrl: "https://www.photoroom.com/blog/rss.xml",
    htmlUrl: "https://www.photoroom.com/blog",
    language: "en",
    category: "AI图像",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "remove-bg-blog",
    name: "Remove.bg Blog",
    xmlUrl: "https://www.remove.bg/blog/rss.xml",
    htmlUrl: "https://www.remove.bg/blog",
    language: "en",
    category: "AI图像",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "jan-ai-blog",
    name: "Jan AI Blog",
    xmlUrl: "https://jan.ai/blog/rss.xml",
    htmlUrl: "https://jan.ai/blog",
    language: "en",
    category: "本地LLM",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "ollama-blog",
    name: "Ollama Blog",
    xmlUrl: "https://ollama.com/blog/rss.xml",
    htmlUrl: "https://ollama.com/blog",
    language: "en",
    category: "本地LLM",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "lm-studio-blog",
    name: "LM Studio Blog",
    xmlUrl: "https://lmstudio.ai/blog/rss.xml",
    htmlUrl: "https://lmstudio.ai/blog",
    language: "en",
    category: "本地LLM",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "gpt4all-blog",
    name: "GPT4All Blog",
    xmlUrl: "https://www.nomic.ai/blog/rss.xml",
    htmlUrl: "https://www.nomic.ai/blog",
    language: "en",
    category: "本地LLM",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "llamacpp-blog",
    name: "llama.cpp Blog",
    xmlUrl: "https://github.com/ggerganov/llama.cpp/releases.atom",
    htmlUrl: "https://github.com/ggerganov/llama.cpp/releases",
    language: "en",
    category: "本地LLM",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "koboldcpp-blog",
    name: "KoboldCpp Blog",
    xmlUrl: "https://github.com/LostRuins/koboldcpp/releases.atom",
    htmlUrl: "https://github.com/LostRuins/koboldcpp/releases",
    language: "en",
    category: "本地LLM",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "text-generation-webui-blog",
    name: "Text Generation WebUI",
    xmlUrl: "https://github.com/oobabooga/text-generation-webui/releases.atom",
    htmlUrl: "https://github.com/oobabooga/text-generation-webui",
    language: "en",
    category: "本地LLM",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "comfyui-blog",
    name: "ComfyUI Blog",
    xmlUrl: "https://github.com/comfyanonymous/ComfyUI/releases.atom",
    htmlUrl: "https://github.com/comfyanonymous/ComfyUI",
    language: "en",
    category: "AI绘画",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "invoke-ai-blog",
    name: "Invoke AI Blog",
    xmlUrl: "https://invoke-ai.github.io/InvokeAI/blog/rss.xml",
    htmlUrl: "https://invoke-ai.github.io/InvokeAI/blog",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "automatic1111-blog",
    name: "AUTOMATIC1111 Blog",
    xmlUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases.atom",
    htmlUrl: "https://github.com/AUTOMATIC1111/stable-diffusion-webui",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "fooocus-blog",
    name: "Fooocus Blog",
    xmlUrl: "https://github.com/lllyasviel/Fooocus/releases.atom",
    htmlUrl: "https://github.com/lllyasviel/Fooocus",
    language: "en",
    category: "AI绘画",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "midjourney-blog",
    name: "Midjourney Blog",
    xmlUrl: "https://midjourney.com/blog/rss.xml",
    htmlUrl: "https://midjourney.com/blog",
    language: "en",
    category: "AI绘画",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "openrouter-blog",
    name: "OpenRouter Blog",
    xmlUrl: "https://openrouter.ai/blog/rss.xml",
    htmlUrl: "https://openrouter.ai/blog",
    language: "en",
    category: "AI模型聚合",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "unify-blog",
    name: "Unify Blog",
    xmlUrl: "https://unify.ai/blog/rss.xml",
    htmlUrl: "https://unify.ai/blog",
    language: "en",
    category: "AI基础设施",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "fallacious-blog",
    name: "Fallacious Blog",
    xmlUrl: "https://fallacious.ai/blog/rss.xml",
    htmlUrl: "https://fallacious.ai/blog",
    language: "en",
    category: "AI推理",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "sf-compute-blog",
    name: "SF Compute Blog",
    xmlUrl: "https://sfcompute.com/blog/rss.xml",
    htmlUrl: "https://sfcompute.com/blog",
    language: "en",
    category: "AI算力",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "lambda-blog",
    name: "Lambda Blog",
    xmlUrl: "https://lambdalabs.com/blog/rss.xml",
    htmlUrl: "https://lambdalabs.com/blog",
    language: "en",
    category: "AI算力",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "coreweave-blog",
    name: "CoreWeave Blog",
    xmlUrl: "https://coreweave.com/blog/rss.xml",
    htmlUrl: "https://coreweave.com/blog",
    language: "en",
    category: "AI算力",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "vast-ai-blog",
    name: "Vast.ai Blog",
    xmlUrl: "https://vast.ai/blog/rss.xml",
    htmlUrl: "https://vast.ai/blog",
    language: "en",
    category: "AI算力",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "shadeform-blog",
    name: "Shadeform Blog",
    xmlUrl: "https://shadeform.ai/blog/rss.xml",
    htmlUrl: "https://shadeform.ai/blog",
    language: "en",
    category: "AI算力",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "tensorwave-blog",
    name: "TensorWave Blog",
    xmlUrl: "https://tensorwave.com/blog/rss.xml",
    htmlUrl: "https://tensorwave.com/blog",
    language: "en",
    category: "AI算力",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "fal-ai-blog",
    name: "fal.ai Blog",
    xmlUrl: "https://fal.ai/blog/rss.xml",
    htmlUrl: "https://fal.ai/blog",
    language: "en",
    category: "AI模型托管",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "banana-dev-blog",
    name: "Banana.dev Blog",
    xmlUrl: "https://www.banana.dev/blog/rss.xml",
    htmlUrl: "https://www.banana.dev/blog",
    language: "en",
    category: "AI模型托管",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "cerebrium-blog",
    name: "Cerebrium Blog",
    xmlUrl: "https://www.cerebrium.ai/blog/rss.xml",
    htmlUrl: "https://www.cerebrium.ai/blog",
    language: "en",
    category: "AI基础设施",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "bentoml-blog",
    name: "BentoML Blog",
    xmlUrl: "https://www.bentoml.com/blog/rss.xml",
    htmlUrl: "https://www.bentoml.com/blog",
    language: "en",
    category: "AI服务化",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "triton-blog",
    name: "Triton Blog",
    xmlUrl: "https://openai.com/research/triton/rss.xml",
    htmlUrl: "https://openai.com/research/triton",
    language: "en",
    category: "AI编译器",
    priority: "low",
    type: "official",
    isActive: false,
  },
];

// 英文科技媒体 - 中频更新
export const ENGLISH_TECH_MEDIA: RSSSource[] = [
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    xmlUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    htmlUrl: "https://techcrunch.com/category/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "the-verge-ai",
    name: "The Verge AI",
    xmlUrl: "https://www.theverge.com/ai-artificial-intelligence/rss/index.xml",
    htmlUrl: "https://www.theverge.com/ai-artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "wired-ai",
    name: "Wired AI",
    xmlUrl: "https://www.wired.com/tag/artificial-intelligence/feed/",
    htmlUrl: "https://www.wired.com/tag/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "mit-tech-review",
    name: "MIT Technology Review",
    xmlUrl: "https://www.technologyreview.com/feed/",
    htmlUrl: "https://www.technologyreview.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "venturebeat-ai",
    name: "VentureBeat AI",
    xmlUrl: "https://venturebeat.com/category/ai/feed/",
    htmlUrl: "https://venturebeat.com/category/ai",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "ai-news",
    name: "AI News",
    xmlUrl: "https://www.artificialintelligence-news.com/feed/",
    htmlUrl: "https://www.artificialintelligence-news.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "analytics-india",
    name: "Analytics India Magazine",
    xmlUrl: "https://analyticsindiamag.com/feed/",
    htmlUrl: "https://analyticsindiamag.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "synced-review",
    name: "Synced Review",
    xmlUrl: "https://syncedreview.com/feed/",
    htmlUrl: "https://syncedreview.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "towards-data-science",
    name: "Towards Data Science",
    xmlUrl: "https://towardsdatascience.com/feed",
    htmlUrl: "https://towardsdatascience.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "arxiv-blog",
    name: "arXiv Blog",
    xmlUrl: "https://blog.arxiv.org/feed/",
    htmlUrl: "https://blog.arxiv.org",
    language: "en",
    category: "学术",
    priority: "medium",
    type: "academic",
    isActive: false,
  },
  {
    id: "import-ai",
    name: "Import AI",
    xmlUrl: "https://importai.substack.com/feed",
    htmlUrl: "https://importai.substack.com",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "the-batch",
    name: "The Batch",
    xmlUrl: "https://www.deeplearning.ai/the-batch/rss/",
    htmlUrl: "https://www.deeplearning.ai/the-batch",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "last-week-ai",
    name: "Last Week in AI",
    xmlUrl: "https://lastweekin.ai/feed",
    htmlUrl: "https://lastweekin.ai",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: false,
  },
];

// 学术/研究机构 - 低频更新
export const ACADEMIC_SOURCES: RSSSource[] = [
  {
    id: "berkeley-ai",
    name: "Berkeley AI Research",
    xmlUrl: "http://bair.berkeley.edu/blog/feed.xml",
    htmlUrl: "http://bair.berkeley.edu/blog",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
  {
    id: "stanford-hai",
    name: "Stanford HAI",
    xmlUrl: "https://hai.stanford.edu/news/rss.xml",
    htmlUrl: "https://hai.stanford.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
  {
    id: "mit-csail",
    name: "MIT CSAIL",
    xmlUrl: "https://www.csail.mit.edu/news/rss.xml",
    htmlUrl: "https://www.csail.mit.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
  {
    id: "cmu-ai",
    name: "CMU AI",
    xmlUrl: "https://www.cmu.edu/news/rss.xml",
    htmlUrl: "https://www.cmu.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
  {
    id: "papers-with-code",
    name: "Papers With Code",
    xmlUrl: "https://paperswithcode.com/rss",
    htmlUrl: "https://paperswithcode.com",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
];

// Hacker News 顶级技术博客
export const HN_TOP_BLOGS: RSSSource[] = [
  {
    id: "simon-willison",
    name: "Simon Willison",
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "https://simonwillison.net",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "paul-graham",
    name: "Paul Graham",
    xmlUrl: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
    htmlUrl: "https://paulgraham.com",
    language: "en",
    category: "观点",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "dan-abramov",
    name: "Dan Abramov",
    xmlUrl: "https://overreacted.io/rss.xml",
    htmlUrl: "https://overreacted.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "gwern",
    name: "Gwern",
    xmlUrl: "https://gwern.substack.com/feed",
    htmlUrl: "https://gwern.net",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "krebs-security",
    name: "Krebs on Security",
    xmlUrl: "https://krebsonsecurity.com/feed/",
    htmlUrl: "https://krebsonsecurity.com",
    language: "en",
    category: "安全",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "antirez",
    name: "Antirez",
    xmlUrl: "http://antirez.com/rss",
    htmlUrl: "http://antirez.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "daring-fireball",
    name: "Daring Fireball",
    xmlUrl: "https://daringfireball.net/feeds/main",
    htmlUrl: "https://daringfireball.net",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "troy-hunt",
    name: "Troy Hunt",
    xmlUrl: "https://www.troyhunt.com/rss/",
    htmlUrl: "https://troyhunt.com",
    language: "en",
    category: "安全",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "mitchell-hashimoto",
    name: "Mitchell Hashimoto",
    xmlUrl: "https://mitchellh.com/feed.xml",
    htmlUrl: "https://mitchellh.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "matklad",
    name: "matklad",
    xmlUrl: "https://matklad.github.io/feed.xml",
    htmlUrl: "https://matklad.github.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "gary-marcus",
    name: "Gary Marcus",
    xmlUrl: "https://garymarcus.substack.com/feed",
    htmlUrl: "https://garymarcus.substack.com",
    language: "en",
    category: "观点",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "max-woolf",
    name: "Max Woolf",
    xmlUrl: "https://minimaxir.com/index.xml",
    htmlUrl: "https://minimaxir.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "george-hotz",
    name: "George Hotz",
    xmlUrl: "https://geohot.github.io/blog/feed.xml",
    htmlUrl: "https://geohot.github.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "jim-nielsen",
    name: "Jim Nielsen",
    xmlUrl: "https://blog.jim-nielsen.com/feed.xml",
    htmlUrl: "https://blog.jim-nielsen.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "geoffrey-litt",
    name: "Geoffrey Litt",
    xmlUrl: "https://www.geoffreylitt.com/feed.xml",
    htmlUrl: "https://www.geoffreylitt.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
];

// ============ 中文权威源 (30+) ============

// 中文 AI 媒体
export const CHINESE_AI_MEDIA: RSSSource[] = [
  {
    id: "jiqizhixin",
    name: "机器之心",
    xmlUrl: "https://www.jiqizhixin.com/rss",
    htmlUrl: "https://www.jiqizhixin.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "qbitai",
    name: "量子位",
    xmlUrl: "https://www.qbitai.com/feed",
    htmlUrl: "https://www.qbitai.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "leiphone",
    name: "雷锋网 AI",
    xmlUrl: "https://www.leiphone.com/rss",
    htmlUrl: "https://www.leiphone.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: false,
  },
  {
    id: "ainews",
    name: "新智元",
    xmlUrl: "https://www.ainews.cn/rss",
    htmlUrl: "https://www.ainews.cn",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: false,
  },
  {
    id: "infoq-cn",
    name: "InfoQ 中文",
    xmlUrl: "https://www.infoq.cn/rss",
    htmlUrl: "https://www.infoq.cn",
    language: "zh",
    category: "技术媒体",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "oschina",
    name: "开源中国",
    xmlUrl: "https://www.oschina.net/rss",
    htmlUrl: "https://www.oschina.net",
    language: "zh",
    category: "开源社区",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "csdn-ai",
    name: "CSDN AI专栏",
    xmlUrl: "https://blog.csdn.net/rss",
    htmlUrl: "https://csdn.net",
    language: "zh",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "36kr",
    name: "36氪",
    xmlUrl: "https://36kr.com/feed",
    htmlUrl: "https://36kr.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "huxiu",
    name: "虎嗅",
    xmlUrl: "https://www.huxiu.com/rss",
    htmlUrl: "https://www.huxiu.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "pingwest",
    name: "品玩",
    xmlUrl: "https://www.pingwest.com/rss",
    htmlUrl: "https://www.pingwest.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "solidot",
    name: "Solidot",
    xmlUrl: "https://www.solidot.org/rss",
    htmlUrl: "https://www.solidot.org",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
];

// 中文开发者博客
export const CHINESE_DEV_BLOGS: RSSSource[] = [
  {
    id: "ruanyifeng",
    name: "阮一峰",
    xmlUrl: "https://www.ruanyifeng.com/blog/atom.xml",
    htmlUrl: "https://www.ruanyifeng.com/blog",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "zhangxinxu",
    name: "张鑫旭",
    xmlUrl: "https://www.zhangxinxu.com/wordpress/feed/",
    htmlUrl: "https://www.zhangxinxu.com",
    language: "zh",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "coolshell",
    name: "酷壳",
    xmlUrl: "https://coolshell.cn/feed",
    htmlUrl: "https://coolshell.cn",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "juejin",
    name: "掘金",
    xmlUrl: "https://juejin.cn/rss",
    htmlUrl: "https://juejin.cn",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
];

// 中国科技公司 AI 博客
export const CHINESE_TECH_COMPANIES: RSSSource[] = [
  {
    id: "tencent-ai-lab",
    name: "腾讯 AI Lab",
    xmlUrl: "https://ai.tencent.com/ailab/rss",
    htmlUrl: "https://ai.tencent.com/ailab",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "alibaba-tech",
    name: "阿里技术",
    xmlUrl: "https://developer.aliyun.com/group/rss",
    htmlUrl: "https://developer.aliyun.com",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "baidu-research-zh",
    name: "百度研究院",
    xmlUrl: "http://research.baidu.com/feed",
    htmlUrl: "http://research.baidu.com",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "bytedance-tech",
    name: "字节跳动技术博客",
    xmlUrl: "https://tech.bytedance.net/rss",
    htmlUrl: "https://tech.bytedance.net",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "baai",
    name: "智源研究院",
    xmlUrl: "https://www.baai.ac.cn/rss",
    htmlUrl: "https://www.baai.ac.cn",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "academic",
    isActive: false,
  },
  {
    id: "tsinghua-air",
    name: "清华 AIR",
    xmlUrl: "https://air.tsinghua.edu.cn/rss",
    htmlUrl: "https://air.tsinghua.edu.cn",
    language: "zh",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
  {
    id: "pku-ai",
    name: "北大 AI",
    xmlUrl: "https://www.ai.pku.edu.cn/rss",
    htmlUrl: "https://www.ai.pku.edu.cn",
    language: "zh",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: false,
  },
];

// ============ Twitter 账号源 (通过 RSSHub) ============

export const TWITTER_RSS_SOURCES: RSSSource[] = [
  {
    id: "twitter-openai",
    name: "OpenAI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/OpenAI"),
    htmlUrl: "https://twitter.com/OpenAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-anthropic",
    name: "Anthropic Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/AnthropicAI"),
    htmlUrl: "https://twitter.com/AnthropicAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-deepmind",
    name: "DeepMind Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/GoogleDeepMind"),
    htmlUrl: "https://twitter.com/GoogleDeepMind",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-metaai",
    name: "Meta AI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/MetaAI"),
    htmlUrl: "https://twitter.com/MetaAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-xai",
    name: "xAI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/xAI"),
    htmlUrl: "https://twitter.com/xAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-karpathy",
    name: "Andrej Karpathy",
    xmlUrl: getRsshubUrl("/twitter/user/karpathy"),
    htmlUrl: "https://twitter.com/karpathy",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-ylecun",
    name: "Yann LeCun",
    xmlUrl: getRsshubUrl("/twitter/user/ylecun"),
    htmlUrl: "https://twitter.com/ylecun",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: false,
  },
  {
    id: "twitter-sama",
    name: "Sam Altman",
    xmlUrl: getRsshubUrl("/twitter/user/sama"),
    htmlUrl: "https://twitter.com/sama",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: false,
  },
];

// ============ Reddit AI 社区板块 (12+) ============

export const REDDIT_AI_SOURCES: RSSSource[] = [
  {
    id: "reddit-machinelearning",
    name: "r/MachineLearning",
    xmlUrl: getRsshubUrl("/reddit/r/MachineLearning"),
    htmlUrl: "https://www.reddit.com/r/MachineLearning/",
    language: "en",
    category: "AI研究",
    priority: "high",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-artificial",
    name: "r/artificial",
    xmlUrl: getRsshubUrl("/reddit/r/artificial"),
    htmlUrl: "https://www.reddit.com/r/artificial/",
    language: "en",
    category: "AI资讯",
    priority: "high",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-singularity",
    name: "r/singularity",
    xmlUrl: getRsshubUrl("/reddit/r/singularity"),
    htmlUrl: "https://www.reddit.com/r/singularity/",
    language: "en",
    category: "AI趋势",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-localllama",
    name: "r/LocalLLaMA",
    xmlUrl: getRsshubUrl("/reddit/r/LocalLLaMA"),
    htmlUrl: "https://www.reddit.com/r/LocalLLaMA/",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-chatgpt",
    name: "r/ChatGPT",
    xmlUrl: getRsshubUrl("/reddit/r/ChatGPT"),
    htmlUrl: "https://www.reddit.com/r/ChatGPT/",
    language: "en",
    category: "ChatGPT",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-claudeai",
    name: "r/ClaudeAI",
    xmlUrl: getRsshubUrl("/reddit/r/ClaudeAI"),
    htmlUrl: "https://www.reddit.com/r/ClaudeAI/",
    language: "en",
    category: "Claude",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-openai",
    name: "r/OpenAI",
    xmlUrl: getRsshubUrl("/reddit/r/OpenAI"),
    htmlUrl: "https://www.reddit.com/r/OpenAI/",
    language: "en",
    category: "OpenAI",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-stablediffusion",
    name: "r/StableDiffusion",
    xmlUrl: getRsshubUrl("/reddit/r/StableDiffusion"),
    htmlUrl: "https://www.reddit.com/r/StableDiffusion/",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-midjourney",
    name: "r/midjourney",
    xmlUrl: getRsshubUrl("/reddit/r/midjourney"),
    htmlUrl: "https://www.reddit.com/r/midjourney/",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-aivideo",
    name: "r/AIvideo",
    xmlUrl: getRsshubUrl("/reddit/r/AIvideo"),
    htmlUrl: "https://www.reddit.com/r/AIvideo/",
    language: "en",
    category: "AI视频",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-aiprogramming",
    name: "r/AIprogramming",
    xmlUrl: getRsshubUrl("/reddit/r/AIprogramming"),
    htmlUrl: "https://www.reddit.com/r/AIprogramming/",
    language: "en",
    category: "AI编程",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "reddit-aiweirdness",
    name: "r/aiwierdness",
    xmlUrl: getRsshubUrl("/reddit/r/aiwierdness"),
    htmlUrl: "https://www.reddit.com/r/aiwierdness/",
    language: "en",
    category: "AI趣闻",
    priority: "low",
    type: "community",
    isActive: false,
  },
];

// ============ 其他社交媒体/社区 (Hacker News等) ============

export const COMMUNITY_SOURCES: RSSSource[] = [
  {
    id: "hn-ai",
    name: "Hacker News AI",
    xmlUrl: "https://hnrss.org/newest?q=artificial+intelligence+OR+machine+learning+OR+LLM+OR+GPT",
    htmlUrl: "https://news.ycombinator.com",
    language: "en",
    category: "社区",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "github-trending",
    name: "GitHub Trending AI",
    xmlUrl: "https://github.com/trending/artificial-intelligence",
    htmlUrl: "https://github.com/trending",
    language: "en",
    category: "开源",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "product-hunt-ai",
    name: "Product Hunt AI",
    xmlUrl: "https://www.producthunt.com/topics/artificial-intelligence/rss",
    htmlUrl: "https://www.producthunt.com/topics/artificial-intelligence",
    language: "en",
    category: "产品",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "lobsters-ai",
    name: "Lobsters AI",
    xmlUrl: "https://lobste.rs/t/ai.rss",
    htmlUrl: "https://lobste.rs/t/ai",
    language: "en",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "hackernews",
    name: "Hacker News",
    xmlUrl: "https://hnrss.org/frontpage",
    htmlUrl: "https://news.ycombinator.com",
    language: "en",
    category: "社区",
    priority: "medium",
    type: "community",
    isActive: false,
  },
  {
    id: "slashdot-ai",
    name: "Slashdot AI",
    xmlUrl: "http://rss.slashdot.org/Slashdot/slashdotAI",
    htmlUrl: "https://slashdot.org/tag/ai",
    language: "en",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
];

// 更多英文科技媒体和博客
export const ADDITIONAL_ENGLISH_SOURCES: RSSSource[] = [
  {
    id: "zdnet-ai",
    name: "ZDNet AI",
    xmlUrl: "https://www.zdnet.com/topic/artificial-intelligence/rss.xml",
    htmlUrl: "https://www.zdnet.com/topic/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "venturebeat",
    name: "VentureBeat",
    xmlUrl: "https://venturebeat.com/feed/",
    htmlUrl: "https://venturebeat.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "fastml",
    name: "FastML",
    xmlUrl: "http://fastml.com/atom.xml",
    htmlUrl: "http://fastml.com",
    language: "en",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "distill",
    name: "Distill.pub",
    xmlUrl: "https://distill.pub/rss.xml",
    htmlUrl: "https://distill.pub",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "academic",
    isActive: false,
  },
  {
    id: "pytorch-blog",
    name: "PyTorch Blog",
    xmlUrl: "https://pytorch.org/blog/atom.xml",
    htmlUrl: "https://pytorch.org/blog",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "tensorflow-blog",
    name: "TensorFlow Blog",
    xmlUrl: "https://blog.tensorflow.org/feeds/posts/default",
    htmlUrl: "https://blog.tensorflow.org",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "jax-blog",
    name: "JAX Blog",
    xmlUrl: "https://jax.readthedocs.io/en/latest/rss.xml",
    htmlUrl: "https://jax.readthedocs.io",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "hugging-face-papers",
    name: "Hugging Face Papers",
    xmlUrl: "https://huggingface.co/papers/feed.xml",
    htmlUrl: "https://huggingface.co/papers",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "eleutherai-blog",
    name: "EleutherAI Blog",
    xmlUrl: "https://blog.eleuther.ai/feed.xml",
    htmlUrl: "https://blog.eleuther.ai",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "scale-ai-blog",
    name: "Scale AI Blog",
    xmlUrl: "https://scale.com/blog/rss.xml",
    htmlUrl: "https://scale.com/blog",
    language: "en",
    category: "AI数据",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "weaviate-blog",
    name: "Weaviate Blog",
    xmlUrl: "https://weaviate.io/blog/rss.xml",
    htmlUrl: "https://weaviate.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "pinecone-blog",
    name: "Pinecone Blog",
    xmlUrl: "https://www.pinecone.io/blog/feed/",
    htmlUrl: "https://www.pinecone.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "langchain-blog",
    name: "LangChain Blog",
    xmlUrl: "https://blog.langchain.dev/rss/",
    htmlUrl: "https://blog.langchain.dev",
    language: "en",
    category: "AI框架",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "llamaindex-blog",
    name: "LlamaIndex Blog",
    xmlUrl: "https://blog.llamaindex.ai/feed",
    htmlUrl: "https://blog.llamaindex.ai",
    language: "en",
    category: "AI框架",
    priority: "high",
    type: "official",
    isActive: false,
  },
  {
    id: "weights-biases",
    name: "Weights & Biases",
    xmlUrl: "https://wandb.ai/site/rss.xml",
    htmlUrl: "https://wandb.ai/site",
    language: "en",
    category: "MLOps",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "neptune-ai",
    name: "Neptune.ai",
    xmlUrl: "https://neptune.ai/blog/feed",
    htmlUrl: "https://neptune.ai/blog",
    language: "en",
    category: "MLOps",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "arize-ai",
    name: "Arize AI",
    xmlUrl: "https://arize.com/blog/feed/",
    htmlUrl: "https://arize.com/blog",
    language: "en",
    category: "MLOps",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "fiddler-ai",
    name: "Fiddler AI",
    xmlUrl: "https://www.fiddler.ai/blog/rss.xml",
    htmlUrl: "https://www.fiddler.ai/blog",
    language: "en",
    category: "AI可解释性",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "snorkel-ai",
    name: "Snorkel AI",
    xmlUrl: "https://snorkel.ai/blog/feed/",
    htmlUrl: "https://snorkel.ai/blog",
    language: "en",
    category: "数据标注",
    priority: "low",
    type: "official",
    isActive: false,
  },
  {
    id: "scale-nucleus",
    name: "Scale Nucleus",
    xmlUrl: "https://scale.com/nucleus/rss.xml",
    htmlUrl: "https://scale.com/nucleus",
    language: "en",
    category: "AI数据",
    priority: "low",
    type: "official",
    isActive: false,
  },
];

// 更多中文源
export const ADDITIONAL_CHINESE_SOURCES: RSSSource[] = [
  {
    id: "ai-era",
    name: "AI时代",
    xmlUrl: "https://www.aitimes.cn/rss",
    htmlUrl: "https://www.aitimes.cn",
    language: "zh",
    category: "AI媒体",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "deeptech",
    name: "DeepTech深科技",
    xmlUrl: "https://www.deeptechchina.com/rss",
    htmlUrl: "https://www.deeptechchina.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "ifanr",
    name: "爱范儿",
    xmlUrl: "https://www.ifanr.com/feed",
    htmlUrl: "https://www.ifanr.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "geekpark",
    name: "极客公园",
    xmlUrl: "https://www.geekpark.net/rss",
    htmlUrl: "https://www.geekpark.net",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "techweb",
    name: "TechWeb",
    xmlUrl: "http://www.techweb.com.cn/rss/focus.xml",
    htmlUrl: "http://www.techweb.com.cn",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "cnbeta",
    name: "cnBeta",
    xmlUrl: "https://www.cnbeta.com/backend.php",
    htmlUrl: "https://www.cnbeta.com",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "segmentfault",
    name: "SegmentFault",
    xmlUrl: "https://segmentfault.com/feeds",
    htmlUrl: "https://segmentfault.com",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "v2ex",
    name: "V2EX",
    xmlUrl: "https://www.v2ex.com/index.xml",
    htmlUrl: "https://www.v2ex.com",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "zhihu-ai",
    name: "知乎 AI话题",
    xmlUrl: "https://www.zhihu.com/rss/people/activities/ai",
    htmlUrl: "https://www.zhihu.com/topic/19559450/hot",
    language: "zh",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: false,
  },
  {
    id: "huawei-cloud",
    name: "华为云",
    xmlUrl: "https://www.huaweicloud.com/rss/news.xml",
    htmlUrl: "https://www.huaweicloud.com",
    language: "zh",
    category: "云服务",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "jd-ai",
    name: "京东 AI",
    xmlUrl: "https://ai.jd.com/rss",
    htmlUrl: "https://ai.jd.com",
    language: "zh",
    category: "AI应用",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "meituan-tech",
    name: "美团技术团队",
    xmlUrl: "https://tech.meituan.com/feed/",
    htmlUrl: "https://tech.meituan.com",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: false,
  },
  {
    id: "netease-tech",
    name: "网易智能",
    xmlUrl: "http://tech.163.com/special/00097UHL/rss_ai.xml",
    htmlUrl: "http://tech.163.com/ai",
    language: "zh",
    category: "AI媒体",
    priority: "medium",
    type: "media",
    isActive: false,
  },
  {
    id: "sina-tech",
    name: "新浪科技 AI",
    xmlUrl: "https://tech.sina.com.cn/roll/rollnews.shtml#pageid=372&lid=2431&k=&num=50&page=1",
    htmlUrl: "https://tech.sina.com.cn/ai",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: false,
  },
  {
    id: "shenzhen-tech",
    name: "深圳湾",
    xmlUrl: "https://www.shenzhenware.com/rss",
    htmlUrl: "https://www.shenzhenware.com",
    language: "zh",
    category: "硬件AI",
    priority: "low",
    type: "media",
    isActive: false,
  },
];

// ============ 合并所有源 ============

export const ALL_RSS_SOURCES: RSSSource[] = [
  ...AI_COMPANY_BLOGS,
  ...ENGLISH_TECH_MEDIA,
  ...ACADEMIC_SOURCES,
  ...HN_TOP_BLOGS,
  ...CHINESE_AI_MEDIA,
  ...CHINESE_DEV_BLOGS,
  ...CHINESE_TECH_COMPANIES,
  ...COMMUNITY_SOURCES,
  ...ADDITIONAL_ENGLISH_SOURCES,
  ...ADDITIONAL_CHINESE_SOURCES,
  ...REDDIT_AI_SOURCES,
  ...TWITTER_RSS_SOURCES,
];

// 统计信息
export function getSourcesStats(): {
  total: number;
  english: number;
  chinese: number;
  highPriority: number;
  mediumPriority: number;
  lowPriority: number;
  byType: Record<SourceType, number>;
} {
  return {
    total: ALL_RSS_SOURCES.length,
    english: ALL_RSS_SOURCES.filter((s) => s.language === "en").length,
    chinese: ALL_RSS_SOURCES.filter((s) => s.language === "zh").length,
    highPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "high").length,
    mediumPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "medium").length,
    lowPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "low").length,
    byType: {
      official: ALL_RSS_SOURCES.filter((s) => s.type === "official").length,
      media: ALL_RSS_SOURCES.filter((s) => s.type === "media").length,
      community: ALL_RSS_SOURCES.filter((s) => s.type === "community").length,
      academic: ALL_RSS_SOURCES.filter((s) => s.type === "academic").length,
      social: ALL_RSS_SOURCES.filter((s) => s.type === "social").length,
    },
  };
}

// 按优先级获取源
export function getSourcesByPriority(priority: SourcePriority): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.priority === priority && s.isActive);
}

// 按类型获取源
export function getSourcesByType(type: SourceType): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.type === type && s.isActive);
}

// 按语言获取源
export function getSourcesByLanguage(lang: "zh" | "en" | "all"): RSSSource[] {
  if (lang === "all") return ALL_RSS_SOURCES.filter((s) => s.isActive);
  return ALL_RSS_SOURCES.filter((s) => s.language === lang && s.isActive);
}

// 获取活跃的源
export function getActiveSources(): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.isActive);
}
