/**
 * RSS 数据源配置
 * 包含 100+ AI 相关数据源：英文权威源、中文权威源、社交媒体/社区
 */

export type SourcePriority = "high" | "medium" | "low";
export type SourceType = "official" | "media" | "community" | "academic" | "social";

export interface RSSSource {
  id: string;
  name: string;
  xmlUrl: string;
  htmlUrl: string;
  language: "zh" | "en";
  category: string;
  priority: SourcePriority;
  type: SourceType;
  isActive: boolean;
  lastCrawled?: string;
}

// ============ 英文权威源 - AI 公司官方博客 (50+) ============

// RSSHub 实例列表
const RSSHUB_INSTANCES = [
  "https://rsshub.rssforever.com",
  "https://rsshub.freedit.eu",
  "https://rsshub.pseudoyu.com",
];

// 获取 RSSHub URL
function getRsshubUrl(path: string): string {
  const instance = RSSHUB_INSTANCES[Math.floor(Math.random() * RSSHUB_INSTANCES.length)];
  return `${instance}${path}`;
}

// 大模型公司官方博客 - 高频更新
export const AI_COMPANY_BLOGS: RSSSource[] = [
  {
    id: "openai-blog",
    name: "OpenAI Blog",
    xmlUrl: getRsshubUrl("/openai/blog"),
    htmlUrl: "https://openai.com/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "openai-research",
    name: "OpenAI Research",
    xmlUrl: "https://openai.com/research/rss.xml",
    htmlUrl: "https://openai.com/research",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "anthropic-news",
    name: "Anthropic News",
    xmlUrl: getRsshubUrl("/anthropic/news"),
    htmlUrl: "https://www.anthropic.com/news",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "anthropic-research",
    name: "Anthropic Research",
    xmlUrl: "https://www.anthropic.com/research/rss.xml",
    htmlUrl: "https://www.anthropic.com/research",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "google-ai-blog",
    name: "Google AI Blog",
    xmlUrl: getRsshubUrl("/google/ai/blog"),
    htmlUrl: "https://ai.googleblog.com",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "deepmind-blog",
    name: "DeepMind Blog",
    xmlUrl: getRsshubUrl("/google/deepmind/blog"),
    htmlUrl: "https://deepmind.google/blog",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "meta-ai-blog",
    name: "Meta AI Blog",
    xmlUrl: getRsshubUrl("/meta/ai/blog"),
    htmlUrl: "https://ai.meta.com/blog",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "xai-blog",
    name: "xAI Blog",
    xmlUrl: "https://x.ai/blog/rss.xml",
    htmlUrl: "https://x.ai/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "mistral-blog",
    name: "Mistral AI Blog",
    xmlUrl: getRsshubUrl("/mistral/blog"),
    htmlUrl: "https://mistral.ai/news",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "cohere-blog",
    name: "Cohere Blog",
    xmlUrl: getRsshubUrl("/cohere/blog"),
    htmlUrl: "https://cohere.com/blog",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "huggingface-blog",
    name: "Hugging Face Blog",
    xmlUrl: "https://huggingface.co/blog/feed.xml",
    htmlUrl: "https://huggingface.co/blog",
    language: "en",
    category: "开源社区",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "stability-blog",
    name: "Stability AI Blog",
    xmlUrl: getRsshubUrl("/stability/blog"),
    htmlUrl: "https://stability.ai/blog",
    language: "en",
    category: "多模态",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "nvidia-blog",
    name: "NVIDIA AI Blog",
    xmlUrl: getRsshubUrl("/nvidia/blog"),
    htmlUrl: "https://blogs.nvidia.com/blog/ai",
    language: "en",
    category: "AI芯片",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "microsoft-ai-blog",
    name: "Microsoft AI Blog",
    xmlUrl: getRsshubUrl("/microsoft/ai/blog"),
    htmlUrl: "https://blogs.microsoft.com/ai",
    language: "en",
    category: "大模型",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "amazon-ai-blog",
    name: "AWS AI Blog",
    xmlUrl: "https://aws.amazon.com/blogs/machine-learning/feed/",
    htmlUrl: "https://aws.amazon.com/blogs/machine-learning",
    language: "en",
    category: "云服务",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "ai2-blog",
    name: "AI2 Blog",
    xmlUrl: "https://blog.allenai.org/feed",
    htmlUrl: "https://blog.allenai.org",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "baidu-research",
    name: "Baidu Research",
    xmlUrl: "http://research.baidu.com/feed",
    htmlUrl: "http://research.baidu.com",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "alibaba-damo",
    name: "Alibaba DAMO Academy",
    xmlUrl: "https://damo.alibaba.com/rss",
    htmlUrl: "https://damo.alibaba.com",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: true,
  },
];

// 英文科技媒体 - 中频更新
export const ENGLISH_TECH_MEDIA: RSSSource[] = [
  {
    id: "techcrunch-ai",
    name: "TechCrunch AI",
    xmlUrl: "https://techcrunch.com/category/artificial-intelligence/feed/",
    htmlUrl: "https://techcrunch.com/category/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "the-verge-ai",
    name: "The Verge AI",
    xmlUrl: "https://www.theverge.com/ai-artificial-intelligence/rss/index.xml",
    htmlUrl: "https://www.theverge.com/ai-artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "wired-ai",
    name: "Wired AI",
    xmlUrl: "https://www.wired.com/tag/artificial-intelligence/feed/",
    htmlUrl: "https://www.wired.com/tag/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "mit-tech-review",
    name: "MIT Technology Review",
    xmlUrl: "https://www.technologyreview.com/feed/",
    htmlUrl: "https://www.technologyreview.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "venturebeat-ai",
    name: "VentureBeat AI",
    xmlUrl: "https://venturebeat.com/category/ai/feed/",
    htmlUrl: "https://venturebeat.com/category/ai",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "ai-news",
    name: "AI News",
    xmlUrl: "https://www.artificialintelligence-news.com/feed/",
    htmlUrl: "https://www.artificialintelligence-news.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "analytics-india",
    name: "Analytics India Magazine",
    xmlUrl: "https://analyticsindiamag.com/feed/",
    htmlUrl: "https://analyticsindiamag.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "synced-review",
    name: "Synced Review",
    xmlUrl: "https://syncedreview.com/feed/",
    htmlUrl: "https://syncedreview.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "towards-data-science",
    name: "Towards Data Science",
    xmlUrl: "https://towardsdatascience.com/feed",
    htmlUrl: "https://towardsdatascience.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "arxiv-blog",
    name: "arXiv Blog",
    xmlUrl: "https://blog.arxiv.org/feed/",
    htmlUrl: "https://blog.arxiv.org",
    language: "en",
    category: "学术",
    priority: "medium",
    type: "academic",
    isActive: true,
  },
  {
    id: "import-ai",
    name: "Import AI",
    xmlUrl: "https://importai.substack.com/feed",
    htmlUrl: "https://importai.substack.com",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "the-batch",
    name: "The Batch",
    xmlUrl: "https://www.deeplearning.ai/the-batch/rss/",
    htmlUrl: "https://www.deeplearning.ai/the-batch",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "last-week-ai",
    name: "Last Week in AI",
    xmlUrl: "https://lastweekin.ai/feed",
    htmlUrl: "https://lastweekin.ai",
    language: "en",
    category: "AI通讯",
    priority: "medium",
    type: "media",
    isActive: true,
  },
];

// 学术/研究机构 - 低频更新
export const ACADEMIC_SOURCES: RSSSource[] = [
  {
    id: "berkeley-ai",
    name: "Berkeley AI Research",
    xmlUrl: "http://bair.berkeley.edu/blog/feed.xml",
    htmlUrl: "http://bair.berkeley.edu/blog",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
  {
    id: "stanford-hai",
    name: "Stanford HAI",
    xmlUrl: "https://hai.stanford.edu/news/rss.xml",
    htmlUrl: "https://hai.stanford.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
  {
    id: "mit-csail",
    name: "MIT CSAIL",
    xmlUrl: "https://www.csail.mit.edu/news/rss.xml",
    htmlUrl: "https://www.csail.mit.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
  {
    id: "cmu-ai",
    name: "CMU AI",
    xmlUrl: "https://www.cmu.edu/news/rss.xml",
    htmlUrl: "https://www.cmu.edu/news",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
  {
    id: "papers-with-code",
    name: "Papers With Code",
    xmlUrl: "https://paperswithcode.com/rss",
    htmlUrl: "https://paperswithcode.com",
    language: "en",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
];

// Hacker News 顶级技术博客
export const HN_TOP_BLOGS: RSSSource[] = [
  {
    id: "simon-willison",
    name: "Simon Willison",
    xmlUrl: "https://simonwillison.net/atom/everything/",
    htmlUrl: "https://simonwillison.net",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "paul-graham",
    name: "Paul Graham",
    xmlUrl: "http://www.aaronsw.com/2002/feeds/pgessays.rss",
    htmlUrl: "https://paulgraham.com",
    language: "en",
    category: "观点",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "dan-abramov",
    name: "Dan Abramov",
    xmlUrl: "https://overreacted.io/rss.xml",
    htmlUrl: "https://overreacted.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "gwern",
    name: "Gwern",
    xmlUrl: "https://gwern.substack.com/feed",
    htmlUrl: "https://gwern.net",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "krebs-security",
    name: "Krebs on Security",
    xmlUrl: "https://krebsonsecurity.com/feed/",
    htmlUrl: "https://krebsonsecurity.com",
    language: "en",
    category: "安全",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "antirez",
    name: "Antirez",
    xmlUrl: "http://antirez.com/rss",
    htmlUrl: "http://antirez.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "daring-fireball",
    name: "Daring Fireball",
    xmlUrl: "https://daringfireball.net/feeds/main",
    htmlUrl: "https://daringfireball.net",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "troy-hunt",
    name: "Troy Hunt",
    xmlUrl: "https://www.troyhunt.com/rss/",
    htmlUrl: "https://troyhunt.com",
    language: "en",
    category: "安全",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "mitchell-hashimoto",
    name: "Mitchell Hashimoto",
    xmlUrl: "https://mitchellh.com/feed.xml",
    htmlUrl: "https://mitchellh.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "matklad",
    name: "matklad",
    xmlUrl: "https://matklad.github.io/feed.xml",
    htmlUrl: "https://matklad.github.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "gary-marcus",
    name: "Gary Marcus",
    xmlUrl: "https://garymarcus.substack.com/feed",
    htmlUrl: "https://garymarcus.substack.com",
    language: "en",
    category: "观点",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "max-woolf",
    name: "Max Woolf",
    xmlUrl: "https://minimaxir.com/index.xml",
    htmlUrl: "https://minimaxir.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "george-hotz",
    name: "George Hotz",
    xmlUrl: "https://geohot.github.io/blog/feed.xml",
    htmlUrl: "https://geohot.github.io",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "jim-nielsen",
    name: "Jim Nielsen",
    xmlUrl: "https://blog.jim-nielsen.com/feed.xml",
    htmlUrl: "https://blog.jim-nielsen.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "geoffrey-litt",
    name: "Geoffrey Litt",
    xmlUrl: "https://www.geoffreylitt.com/feed.xml",
    htmlUrl: "https://www.geoffreylitt.com",
    language: "en",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
];

// ============ 中文权威源 (30+) ============

// 中文 AI 媒体
export const CHINESE_AI_MEDIA: RSSSource[] = [
  {
    id: "jiqizhixin",
    name: "机器之心",
    xmlUrl: "https://www.jiqizhixin.com/rss",
    htmlUrl: "https://www.jiqizhixin.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "qbitai",
    name: "量子位",
    xmlUrl: "https://www.qbitai.com/feed",
    htmlUrl: "https://www.qbitai.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "leiphone",
    name: "雷锋网 AI",
    xmlUrl: "https://www.leiphone.com/rss",
    htmlUrl: "https://www.leiphone.com",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "ainews",
    name: "新智元",
    xmlUrl: "https://www.ainews.cn/rss",
    htmlUrl: "https://www.ainews.cn",
    language: "zh",
    category: "AI媒体",
    priority: "high",
    type: "media",
    isActive: true,
  },
  {
    id: "infoq-cn",
    name: "InfoQ 中文",
    xmlUrl: "https://www.infoq.cn/rss",
    htmlUrl: "https://www.infoq.cn",
    language: "zh",
    category: "技术媒体",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "oschina",
    name: "开源中国",
    xmlUrl: "https://www.oschina.net/rss",
    htmlUrl: "https://www.oschina.net",
    language: "zh",
    category: "开源社区",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "csdn-ai",
    name: "CSDN AI专栏",
    xmlUrl: "https://blog.csdn.net/rss",
    htmlUrl: "https://csdn.net",
    language: "zh",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "36kr",
    name: "36氪",
    xmlUrl: "https://36kr.com/feed",
    htmlUrl: "https://36kr.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "huxiu",
    name: "虎嗅",
    xmlUrl: "https://www.huxiu.com/rss",
    htmlUrl: "https://www.huxiu.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "pingwest",
    name: "品玩",
    xmlUrl: "https://www.pingwest.com/rss",
    htmlUrl: "https://www.pingwest.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "solidot",
    name: "Solidot",
    xmlUrl: "https://www.solidot.org/rss",
    htmlUrl: "https://www.solidot.org",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
];

// 中文开发者博客
export const CHINESE_DEV_BLOGS: RSSSource[] = [
  {
    id: "ruanyifeng",
    name: "阮一峰",
    xmlUrl: "https://www.ruanyifeng.com/blog/atom.xml",
    htmlUrl: "https://www.ruanyifeng.com/blog",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "zhangxinxu",
    name: "张鑫旭",
    xmlUrl: "https://www.zhangxinxu.com/wordpress/feed/",
    htmlUrl: "https://www.zhangxinxu.com",
    language: "zh",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "coolshell",
    name: "酷壳",
    xmlUrl: "https://coolshell.cn/feed",
    htmlUrl: "https://coolshell.cn",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "juejin",
    name: "掘金",
    xmlUrl: "https://juejin.cn/rss",
    htmlUrl: "https://juejin.cn",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
];

// 中国科技公司 AI 博客
export const CHINESE_TECH_COMPANIES: RSSSource[] = [
  {
    id: "tencent-ai-lab",
    name: "腾讯 AI Lab",
    xmlUrl: "https://ai.tencent.com/ailab/rss",
    htmlUrl: "https://ai.tencent.com/ailab",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "alibaba-tech",
    name: "阿里技术",
    xmlUrl: "https://developer.aliyun.com/group/rss",
    htmlUrl: "https://developer.aliyun.com",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "baidu-research-zh",
    name: "百度研究院",
    xmlUrl: "http://research.baidu.com/feed",
    htmlUrl: "http://research.baidu.com",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "bytedance-tech",
    name: "字节跳动技术博客",
    xmlUrl: "https://tech.bytedance.net/rss",
    htmlUrl: "https://tech.bytedance.net",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "baai",
    name: "智源研究院",
    xmlUrl: "https://www.baai.ac.cn/rss",
    htmlUrl: "https://www.baai.ac.cn",
    language: "zh",
    category: "研究",
    priority: "medium",
    type: "academic",
    isActive: true,
  },
  {
    id: "tsinghua-air",
    name: "清华 AIR",
    xmlUrl: "https://air.tsinghua.edu.cn/rss",
    htmlUrl: "https://air.tsinghua.edu.cn",
    language: "zh",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
  {
    id: "pku-ai",
    name: "北大 AI",
    xmlUrl: "https://www.ai.pku.edu.cn/rss",
    htmlUrl: "https://www.ai.pku.edu.cn",
    language: "zh",
    category: "研究",
    priority: "low",
    type: "academic",
    isActive: true,
  },
];

// ============ Twitter 账号源 (通过 RSSHub) ============

export const TWITTER_RSS_SOURCES: RSSSource[] = [
  {
    id: "twitter-openai",
    name: "OpenAI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/OpenAI"),
    htmlUrl: "https://twitter.com/OpenAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-anthropic",
    name: "Anthropic Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/AnthropicAI"),
    htmlUrl: "https://twitter.com/AnthropicAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-deepmind",
    name: "DeepMind Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/GoogleDeepMind"),
    htmlUrl: "https://twitter.com/GoogleDeepMind",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-metaai",
    name: "Meta AI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/MetaAI"),
    htmlUrl: "https://twitter.com/MetaAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-xai",
    name: "xAI Twitter",
    xmlUrl: getRsshubUrl("/twitter/user/xAI"),
    htmlUrl: "https://twitter.com/xAI",
    language: "en",
    category: "官方机构",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-karpathy",
    name: "Andrej Karpathy",
    xmlUrl: getRsshubUrl("/twitter/user/karpathy"),
    htmlUrl: "https://twitter.com/karpathy",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-ylecun",
    name: "Yann LeCun",
    xmlUrl: getRsshubUrl("/twitter/user/ylecun"),
    htmlUrl: "https://twitter.com/ylecun",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: true,
  },
  {
    id: "twitter-sama",
    name: "Sam Altman",
    xmlUrl: getRsshubUrl("/twitter/user/sama"),
    htmlUrl: "https://twitter.com/sama",
    language: "en",
    category: "AI研究者",
    priority: "high",
    type: "social",
    isActive: true,
  },
];

// ============ Reddit AI 社区板块 (12+) ============

export const REDDIT_AI_SOURCES: RSSSource[] = [
  {
    id: "reddit-machinelearning",
    name: "r/MachineLearning",
    xmlUrl: getRsshubUrl("/reddit/r/MachineLearning"),
    htmlUrl: "https://www.reddit.com/r/MachineLearning/",
    language: "en",
    category: "AI研究",
    priority: "high",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-artificial",
    name: "r/artificial",
    xmlUrl: getRsshubUrl("/reddit/r/artificial"),
    htmlUrl: "https://www.reddit.com/r/artificial/",
    language: "en",
    category: "AI资讯",
    priority: "high",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-singularity",
    name: "r/singularity",
    xmlUrl: getRsshubUrl("/reddit/r/singularity"),
    htmlUrl: "https://www.reddit.com/r/singularity/",
    language: "en",
    category: "AI趋势",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-localllama",
    name: "r/LocalLLaMA",
    xmlUrl: getRsshubUrl("/reddit/r/LocalLLaMA"),
    htmlUrl: "https://www.reddit.com/r/LocalLLaMA/",
    language: "en",
    category: "开源模型",
    priority: "high",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-chatgpt",
    name: "r/ChatGPT",
    xmlUrl: getRsshubUrl("/reddit/r/ChatGPT"),
    htmlUrl: "https://www.reddit.com/r/ChatGPT/",
    language: "en",
    category: "ChatGPT",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-claudeai",
    name: "r/ClaudeAI",
    xmlUrl: getRsshubUrl("/reddit/r/ClaudeAI"),
    htmlUrl: "https://www.reddit.com/r/ClaudeAI/",
    language: "en",
    category: "Claude",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-openai",
    name: "r/OpenAI",
    xmlUrl: getRsshubUrl("/reddit/r/OpenAI"),
    htmlUrl: "https://www.reddit.com/r/OpenAI/",
    language: "en",
    category: "OpenAI",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-stablediffusion",
    name: "r/StableDiffusion",
    xmlUrl: getRsshubUrl("/reddit/r/StableDiffusion"),
    htmlUrl: "https://www.reddit.com/r/StableDiffusion/",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-midjourney",
    name: "r/midjourney",
    xmlUrl: getRsshubUrl("/reddit/r/midjourney"),
    htmlUrl: "https://www.reddit.com/r/midjourney/",
    language: "en",
    category: "AI绘画",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-aivideo",
    name: "r/AIvideo",
    xmlUrl: getRsshubUrl("/reddit/r/AIvideo"),
    htmlUrl: "https://www.reddit.com/r/AIvideo/",
    language: "en",
    category: "AI视频",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-aiprogramming",
    name: "r/AIprogramming",
    xmlUrl: getRsshubUrl("/reddit/r/AIprogramming"),
    htmlUrl: "https://www.reddit.com/r/AIprogramming/",
    language: "en",
    category: "AI编程",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "reddit-aiweirdness",
    name: "r/aiwierdness",
    xmlUrl: getRsshubUrl("/reddit/r/aiwierdness"),
    htmlUrl: "https://www.reddit.com/r/aiwierdness/",
    language: "en",
    category: "AI趣闻",
    priority: "low",
    type: "community",
    isActive: true,
  },
];

// ============ 其他社交媒体/社区 (Hacker News等) ============

export const COMMUNITY_SOURCES: RSSSource[] = [
  {
    id: "hn-ai",
    name: "Hacker News AI",
    xmlUrl: "https://hnrss.org/newest?q=artificial+intelligence+OR+machine+learning+OR+LLM+OR+GPT",
    htmlUrl: "https://news.ycombinator.com",
    language: "en",
    category: "社区",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "github-trending",
    name: "GitHub Trending AI",
    xmlUrl: "https://github.com/trending/artificial-intelligence",
    htmlUrl: "https://github.com/trending",
    language: "en",
    category: "开源",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "product-hunt-ai",
    name: "Product Hunt AI",
    xmlUrl: "https://www.producthunt.com/topics/artificial-intelligence/rss",
    htmlUrl: "https://www.producthunt.com/topics/artificial-intelligence",
    language: "en",
    category: "产品",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "lobsters-ai",
    name: "Lobsters AI",
    xmlUrl: "https://lobste.rs/t/ai.rss",
    htmlUrl: "https://lobste.rs/t/ai",
    language: "en",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "hackernews",
    name: "Hacker News",
    xmlUrl: "https://hnrss.org/frontpage",
    htmlUrl: "https://news.ycombinator.com",
    language: "en",
    category: "社区",
    priority: "medium",
    type: "community",
    isActive: true,
  },
  {
    id: "slashdot-ai",
    name: "Slashdot AI",
    xmlUrl: "http://rss.slashdot.org/Slashdot/slashdotAI",
    htmlUrl: "https://slashdot.org/tag/ai",
    language: "en",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
];

// 更多英文科技媒体和博客
export const ADDITIONAL_ENGLISH_SOURCES: RSSSource[] = [
  {
    id: "zdnet-ai",
    name: "ZDNet AI",
    xmlUrl: "https://www.zdnet.com/topic/artificial-intelligence/rss.xml",
    htmlUrl: "https://www.zdnet.com/topic/artificial-intelligence",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "venturebeat",
    name: "VentureBeat",
    xmlUrl: "https://venturebeat.com/feed/",
    htmlUrl: "https://venturebeat.com",
    language: "en",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "fastml",
    name: "FastML",
    xmlUrl: "http://fastml.com/atom.xml",
    htmlUrl: "http://fastml.com",
    language: "en",
    category: "技术博客",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "distill",
    name: "Distill.pub",
    xmlUrl: "https://distill.pub/rss.xml",
    htmlUrl: "https://distill.pub",
    language: "en",
    category: "研究",
    priority: "medium",
    type: "academic",
    isActive: true,
  },
  {
    id: "pytorch-blog",
    name: "PyTorch Blog",
    xmlUrl: "https://pytorch.org/blog/atom.xml",
    htmlUrl: "https://pytorch.org/blog",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "tensorflow-blog",
    name: "TensorFlow Blog",
    xmlUrl: "https://blog.tensorflow.org/feeds/posts/default",
    htmlUrl: "https://blog.tensorflow.org",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "jax-blog",
    name: "JAX Blog",
    xmlUrl: "https://jax.readthedocs.io/en/latest/rss.xml",
    htmlUrl: "https://jax.readthedocs.io",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "hugging-face-papers",
    name: "Hugging Face Papers",
    xmlUrl: "https://huggingface.co/papers/feed.xml",
    htmlUrl: "https://huggingface.co/papers",
    language: "en",
    category: "研究",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "eleutherai-blog",
    name: "EleutherAI Blog",
    xmlUrl: "https://blog.eleuther.ai/feed.xml",
    htmlUrl: "https://blog.eleuther.ai",
    language: "en",
    category: "开源",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "scale-ai-blog",
    name: "Scale AI Blog",
    xmlUrl: "https://scale.com/blog/rss.xml",
    htmlUrl: "https://scale.com/blog",
    language: "en",
    category: "AI数据",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "weaviate-blog",
    name: "Weaviate Blog",
    xmlUrl: "https://weaviate.io/blog/rss.xml",
    htmlUrl: "https://weaviate.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "pinecone-blog",
    name: "Pinecone Blog",
    xmlUrl: "https://www.pinecone.io/blog/feed/",
    htmlUrl: "https://www.pinecone.io/blog",
    language: "en",
    category: "向量数据库",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "langchain-blog",
    name: "LangChain Blog",
    xmlUrl: "https://blog.langchain.dev/rss/",
    htmlUrl: "https://blog.langchain.dev",
    language: "en",
    category: "AI框架",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "llamaindex-blog",
    name: "LlamaIndex Blog",
    xmlUrl: "https://blog.llamaindex.ai/feed",
    htmlUrl: "https://blog.llamaindex.ai",
    language: "en",
    category: "AI框架",
    priority: "high",
    type: "official",
    isActive: true,
  },
  {
    id: "weights-biases",
    name: "Weights & Biases",
    xmlUrl: "https://wandb.ai/site/rss.xml",
    htmlUrl: "https://wandb.ai/site",
    language: "en",
    category: "MLOps",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "neptune-ai",
    name: "Neptune.ai",
    xmlUrl: "https://neptune.ai/blog/feed",
    htmlUrl: "https://neptune.ai/blog",
    language: "en",
    category: "MLOps",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "arize-ai",
    name: "Arize AI",
    xmlUrl: "https://arize.com/blog/feed/",
    htmlUrl: "https://arize.com/blog",
    language: "en",
    category: "MLOps",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "fiddler-ai",
    name: "Fiddler AI",
    xmlUrl: "https://www.fiddler.ai/blog/rss.xml",
    htmlUrl: "https://www.fiddler.ai/blog",
    language: "en",
    category: "AI可解释性",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "snorkel-ai",
    name: "Snorkel AI",
    xmlUrl: "https://snorkel.ai/blog/feed/",
    htmlUrl: "https://snorkel.ai/blog",
    language: "en",
    category: "数据标注",
    priority: "low",
    type: "official",
    isActive: true,
  },
  {
    id: "scale-nucleus",
    name: "Scale Nucleus",
    xmlUrl: "https://scale.com/nucleus/rss.xml",
    htmlUrl: "https://scale.com/nucleus",
    language: "en",
    category: "AI数据",
    priority: "low",
    type: "official",
    isActive: true,
  },
];

// 更多中文源
export const ADDITIONAL_CHINESE_SOURCES: RSSSource[] = [
  {
    id: "ai-era",
    name: "AI时代",
    xmlUrl: "https://www.aitimes.cn/rss",
    htmlUrl: "https://www.aitimes.cn",
    language: "zh",
    category: "AI媒体",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "deeptech",
    name: "DeepTech深科技",
    xmlUrl: "https://www.deeptechchina.com/rss",
    htmlUrl: "https://www.deeptechchina.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "ifanr",
    name: "爱范儿",
    xmlUrl: "https://www.ifanr.com/feed",
    htmlUrl: "https://www.ifanr.com",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "geekpark",
    name: "极客公园",
    xmlUrl: "https://www.geekpark.net/rss",
    htmlUrl: "https://www.geekpark.net",
    language: "zh",
    category: "科技新闻",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "techweb",
    name: "TechWeb",
    xmlUrl: "http://www.techweb.com.cn/rss/focus.xml",
    htmlUrl: "http://www.techweb.com.cn",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "cnbeta",
    name: "cnBeta",
    xmlUrl: "https://www.cnbeta.com/backend.php",
    htmlUrl: "https://www.cnbeta.com",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "segmentfault",
    name: "SegmentFault",
    xmlUrl: "https://segmentfault.com/feeds",
    htmlUrl: "https://segmentfault.com",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "v2ex",
    name: "V2EX",
    xmlUrl: "https://www.v2ex.com/index.xml",
    htmlUrl: "https://www.v2ex.com",
    language: "zh",
    category: "技术社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "zhihu-ai",
    name: "知乎 AI话题",
    xmlUrl: "https://www.zhihu.com/rss/people/activities/ai",
    htmlUrl: "https://www.zhihu.com/topic/19559450/hot",
    language: "zh",
    category: "社区",
    priority: "low",
    type: "community",
    isActive: true,
  },
  {
    id: "huawei-cloud",
    name: "华为云",
    xmlUrl: "https://www.huaweicloud.com/rss/news.xml",
    htmlUrl: "https://www.huaweicloud.com",
    language: "zh",
    category: "云服务",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "jd-ai",
    name: "京东 AI",
    xmlUrl: "https://ai.jd.com/rss",
    htmlUrl: "https://ai.jd.com",
    language: "zh",
    category: "AI应用",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "meituan-tech",
    name: "美团技术团队",
    xmlUrl: "https://tech.meituan.com/feed/",
    htmlUrl: "https://tech.meituan.com",
    language: "zh",
    category: "技术博客",
    priority: "medium",
    type: "official",
    isActive: true,
  },
  {
    id: "netease-tech",
    name: "网易智能",
    xmlUrl: "http://tech.163.com/special/00097UHL/rss_ai.xml",
    htmlUrl: "http://tech.163.com/ai",
    language: "zh",
    category: "AI媒体",
    priority: "medium",
    type: "media",
    isActive: true,
  },
  {
    id: "sina-tech",
    name: "新浪科技 AI",
    xmlUrl: "https://tech.sina.com.cn/roll/rollnews.shtml#pageid=372&lid=2431&k=&num=50&page=1",
    htmlUrl: "https://tech.sina.com.cn/ai",
    language: "zh",
    category: "科技新闻",
    priority: "low",
    type: "media",
    isActive: true,
  },
  {
    id: "shenzhen-tech",
    name: "深圳湾",
    xmlUrl: "https://www.shenzhenware.com/rss",
    htmlUrl: "https://www.shenzhenware.com",
    language: "zh",
    category: "硬件AI",
    priority: "low",
    type: "media",
    isActive: true,
  },
];

// ============ 合并所有源 ============

export const ALL_RSS_SOURCES: RSSSource[] = [
  ...AI_COMPANY_BLOGS,
  ...ENGLISH_TECH_MEDIA,
  ...ACADEMIC_SOURCES,
  ...HN_TOP_BLOGS,
  ...CHINESE_AI_MEDIA,
  ...CHINESE_DEV_BLOGS,
  ...CHINESE_TECH_COMPANIES,
  ...COMMUNITY_SOURCES,
  ...ADDITIONAL_ENGLISH_SOURCES,
  ...ADDITIONAL_CHINESE_SOURCES,
  ...REDDIT_AI_SOURCES,
  ...TWITTER_RSS_SOURCES,
];

// 统计信息
export function getSourcesStats(): {
  total: number;
  english: number;
  chinese: number;
  highPriority: number;
  mediumPriority: number;
  lowPriority: number;
  byType: Record<SourceType, number>;
} {
  return {
    total: ALL_RSS_SOURCES.length,
    english: ALL_RSS_SOURCES.filter((s) => s.language === "en").length,
    chinese: ALL_RSS_SOURCES.filter((s) => s.language === "zh").length,
    highPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "high").length,
    mediumPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "medium").length,
    lowPriority: ALL_RSS_SOURCES.filter((s) => s.priority === "low").length,
    byType: {
      official: ALL_RSS_SOURCES.filter((s) => s.type === "official").length,
      media: ALL_RSS_SOURCES.filter((s) => s.type === "media").length,
      community: ALL_RSS_SOURCES.filter((s) => s.type === "community").length,
      academic: ALL_RSS_SOURCES.filter((s) => s.type === "academic").length,
      social: ALL_RSS_SOURCES.filter((s) => s.type === "social").length,
    },
  };
}

// 按优先级获取源
export function getSourcesByPriority(priority: SourcePriority): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.priority === priority && s.isActive);
}

// 按类型获取源
export function getSourcesByType(type: SourceType): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.type === type && s.isActive);
}

// 按语言获取源
export function getSourcesByLanguage(lang: "zh" | "en" | "all"): RSSSource[] {
  if (lang === "all") return ALL_RSS_SOURCES.filter((s) => s.isActive);
  return ALL_RSS_SOURCES.filter((s) => s.language === lang && s.isActive);
}

// 获取活跃的源
export function getActiveSources(): RSSSource[] {
  return ALL_RSS_SOURCES.filter((s) => s.isActive);
}
